### ISSUE TITLE
Dealing with icons

### ISSUE THREAD

**Issue by iJosephY** [planetteamspeak/ts3phpframework#105]
Hello,
this is just a simple question hope you have answers
i would like to upload  an icon
and assign it to a client 
and if the client have an icon before i would like to get it and delete it
So 
( 
how to
Upload an icon ( and replace if it already exist )
Assign it
Get an icon by id and delete it
)

Thanks

**Comment by ronindesign** [comment]
Please review documentation and forums for examples.
That being said, our documentation could definitely use more examples, so we're sorry about that!

You can search documentation using Google, for example:
`icon site:https://docs.planetteamspeak.com/ts3/php/framework/`

You can also search the forum for examples:
`icon site:https://forum.teamspeak.com/threads/54132-API-TS3-PHP-Framework`

Review the docs for [uploading icon](https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___server.html#a803d31105acaf893fae255222a07d392).

**Uploading an Icon**
https://forum.teamspeak.com/threads/54132-API-TS3-PHP-Framework?p=381629#post381629
_This example also includes assigning an icon to a server group, the process is similar for a user._

**Assigning an Icon**
```php
$ts3->clientGetById(154)->permAssign("i_icon_id", $iconID);
```

**Deleting an Icon**
These [three comments](https://forum.teamspeak.com/threads/54132-API-TS3-PHP-Framework?p=326951#post326951) discuss listing icons using `channelFileList()` (i.e. for channel _0_)  [[ref](https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___server.html#a2cd251e78f9a8d8b2e5ec60274c93bdb)],
and then deleting using `channelFileDelete()` [[ref](https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___server.html#ae6065b306fbfed8f8fd09094724d7cd2)]

**Comment by ronindesign** [comment]
Closing for now, please let us know if you have any follow up questions, or need further assistance!
