### ISSUE TITLE
Creating channel with an icon

### ISSUE THREAD

**Issue by realKitsune** [planetteamspeak/ts3phpframework#108]
Hello. 

I'm trying to make a one-click button to create a private channel.
Here is my actual code:

		$ts3_VirtualServer->channelCreate(array('channel_flag_maxclients_unlimited' => TRUE, 'channel_codec_quality' => 10, 'channel_codec' => TeamSpeak3::CODEC_OPUS_VOICE, 'channel_flag_semi_permanent' => TRUE, 'channel_name' => 'Salon privé de '.$info_isOnlineName, 'channel_topic' => $info_isOnlineProfile, 'channel_icon_id' => $iconeid, 'channel_description' => 'Ceci est la description par défaut. Channel créé le: '.date("d/m/y H:i").' par '.$info_isOnlineName.' [#'.$info_isOnlineDbID.']'));
		$privateChannelList = $ts3_VirtualServer->channelList($privateChannelFilters); 
		foreach ($privateChannelList as $privChannelCount) {
			if($privChannelCount['channel_topic'] == $info_isOnlineProfile){ 
				$ownChannel_cid = $privChannelCount['cid'];
			}
		}

 		$ts3_VirtualServer->clientGetByDbid($info_isOnlineDbID)->setChannelGroup($ownChannel_cid, 27);
 		$ts3_VirtualServer->clientGetByDbid($info_isOnlineDbID)->move($ownChannel_cid);

**'channel_icon_id' => $iconeid** is set : $iconeid = -1452005422;

I checked the icon_id by setting it manually on a channel then checked with 'channel_icon_id' and it's -1452005422. The code works if I remove the icon id flag, it doesn't work when I add it.

Need some help here :)

**Comment by ronindesign** [comment]
Interesting, I'll have to test this locally.

I know there's some specific handling regarding the icon_id, something about max int, signed, etc and some special handling (i.e. this is why there is a negative sign).
I'm not sure if this is the issue you're running into (you could search the forums for related issue with icon_id), but it may also be there is a problem with the `channelCreate()` logic.

In the meantime, as a testing step, you might also try:

- Uploading a fresh icon when you create the channel
- use a different icon which as a smaller `icon_id`, i.e. something less than 2^31 or has less than 10 significant digits.

**Comment by ronindesign** [comment]
Awesome, thanks for the insight @snegrini.

I remember correctly, there's specifically some conversion logic when mapping `icon_id`s between `server` <--> `client`.

I believe Redeemer / YaTQA goes into this a bit on his site somewhere...

In any case, I'll still try to reproduce via framework, would be a great opportunity to add unit tests for icon management.

**Comment by ronindesign** [comment]
Also of possible relevance:
https://forum.teamspeak.com/threads/54132-API-TS3-PHP-Framework?p=453588#post453588

**Comment by ronindesign** [comment]
I'm also finding lots of examples where setting `channel_icon_id` on channel creation is not working:

```php
      $ts3->message("Přidávám dodatečné místnosti...");
      global $chann1, $chann2, $chann3;
      try {
      $chann1 = $ts3->channelCreate(array (
  "channel_name"           => "Additional public room #1",
  "channel_topic"          => "",
  "channel_codec"          => TeamSpeak3::CODEC_OPUS_VOICE,
  "channel_codec_quality"  => 6,
  "channel_flag_permanent" => TRUE,
  "channel_order"          => 370,
  //"channel_icon_id"        => 1513344601,
));
      $chann2 = $ts3->channelCreate(array (
  "channel_name"           => "Additional public room #2",
  "channel_topic"          => "",
  "channel_codec"          => TeamSpeak3::CODEC_OPUS_VOICE,
  "channel_codec_quality"  => 6,
  "channel_flag_permanent" => TRUE,
  //"channel_icon_id"        => 1031730392, //NOT working ATM, need to fix
  "channel_order"          => $chann1,
));}
```

At this point, it's seems a lot like, while `channel_icon_id` is a valid `server property`, it may be that server query does not accept it via `channelcreate` command. [[ref](http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf#page=18)]

I would recommend trying to set icon_id manually after creating channel and see if this works.

**Comment by realKitsune** [comment]
Doesn't work also with

```
$ts3_VirtualServer->execute("channeledit", array("cid" => $ownChannel_cid, "channel_icon_id" => -1452005422));
```

So this value can be grabbed with query but not modified?

Setting it manually works fine but that would not help.
Is there a way then like uploading an icon and setting it directly to the channel with the API? Has someone did it before?

**Comment by realKitsune** [comment]
```
$ts3_VirtualServer->execute("channeledit", array("cid" => $ownChannel_cid, "channel_icon_id" =>  1646637303));
```
Seems to work fine, I think that might be related to negative value of icon_id.

**Comment by ronindesign** [comment]
Does `channelCreate()` work using those same positive values?

If so, this would clearly indicate that there is an issue with the negative numbers.

I'm almost positive this is a classic issue, as I've ran into it a couple times myself, but I thought it was resolved.

**Comment by snegrini** [comment]
This link could help: https://yat.qa/ressourcen/definitionen-und-algorithmen/#icons
It seems that `channeledit` wants a unsigned value.

**Comment by realKitsune** [comment]
> Does `channelCreate()` work using those same positive values?
> 
> If so, this would clearly indicate that there is an issue with the negative numbers.
> 
> I'm almost positive this is a classic issue, as I've ran into it a couple times myself, but I thought it was resolved.

No it doesn't seems to work only when using `channeledit`

**Comment by ronindesign** [comment]
Looks like this solution should work for you. If you're still having issues, please let us know!

**Comment by realKitsune** [comment]
> That's the reason I added `TeamSpeak3_Helper_Convert::iconId()` a while ago... Also, please note that the icon ID is actually a channel permission. There are a few commands where setting the icon ID will work for convenience (if it has been implemented in the TeamSpeak Server)... but I'm not sure if `channelcreate` is one of those.
> 
> I'd recommend setting the channel permission after the channel was created. Here's an example:
> 
> ```
> $channel_id = $server->channelCreate($args);
> $icon_id    = TeamSpeak3_Helper_Convert::iconId(-123);
> 
> $server->channelPermAssign($channel_id, "i_icon_id", $icon_id);
> ```

Just to note: this method still gives me a negative number which doesn't work.
But now it works for my solution. I edited a pixel of the image to change icon_id and I got a positive id.

**Comment by ronindesign** [comment]
Thanks for the report, I'll keep this on the list for testing so we can make sure to iron out how it behaves.

Glad you got it working with a workaround!
