### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by JonErickson** [planetteamspeak/ts3phpframework#109]
Trying to implement this library into a project and I keep receiving a connection refused error.

```
// Create URI component
$uri = "serverquery://username:password@54.200.11.203:10011/";

// Create new object of TS3 PHP Framework class
$teamspeak = new TeamSpeak3();

// Connect to their server
$teamspeak->factory( $uri );
```
I have made sure the TS server has whitelisted the requesting web servers IP, the credentials are correct, ports are properly forwarded etc. I can telnet into the serverquery interface just fine from my workstation. What could I be missing? Thanks!

**Comment by ronindesign** [comment]
There could be networking issues from your web host.

I recommend accessing your webhost via SSH (most shared hosting provides this).

Then attempt to telnet from your webhost to your TS server.

It's clear your TS server's network is accessible externally, but your webhost may have additional configuration that could be interfering.

**Comment by ronindesign** [comment]
Test with python (untested) [[ref](https://serverfault.com/questions/500055/how-to-test-a-connection-without-telnet)]:
_NB: Tested only in Python v3, syntax is similar but different for Python v2._

```python
$ python                          
Python 3.7.0 (default, Jun 29 2018, 20:13:13) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> conn=socket.create_connection(('virtual.ronin.media',10011))
```
Should work (i.e. no output / error), then if it does, you can test further (untested):

```python
>>> input=conn.makefile()
>>> print(input.readline())
TS3

>>> print(input.readline())


>>> print(input.readline())
Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.

>>> conn.sendall(b'use 1\n\r')
>>> print(input.readline())


>>> print(input.readline())
error id=0 msg=ok
```

**Comment by ronindesign** [comment]
It may also be worth opening a ticket with your web host to see if they have any network configuration or outbound firewall rules...

**Comment by ronindesign** [comment]
Closing this for now, please let us know if you're still having trouble connecting to your host.
