### ISSUE TITLE
Get license information

### ISSUE THREAD

**Issue by Sebi94nbg** [planetteamspeak/ts3phpframework#110]
There is no way to get license information from the current connected TeamSpeak instance, or?

Something like this:
- License name (ATHP, AAL, NPL, Unlicensed)
- Max. Virtual Servers (eg. 10)
- Max. Slots (eg. 512)
- Licensed to (eg. Example Community)

**Comment by Sebi94nbg** [comment]
It would be cool, if TeamSpeak would just provide a command to display the current detected license information like I mentioned for only authorized super server admins.

They don't need to show the license key(s) - only the other information, which are useful.

Ok, then I need to check the instance log file for this. I thought there is a trick to get it using a ServerQuery command.

Thanks for your feedback.

**Comment by ronindesign** [comment]
Yeah, I would also like this. I know I could have used this this in some of my projects.

Not much we can do when the TS3 server doesn't have the functionality, it is unfortunate...
