### ISSUE TITLE
Customized TSViewer

### ISSUE THREAD

**Issue by Sebi94nbg** [planetteamspeak/ts3phpframework#111]
Hey,

> Integrated full featured and **customizable** TSViewer interfaces

Is there any documentation with examples, what you can build and which options are available?

**Comment by ronindesign** [comment]
Only examples are found in the [documentation](https://github.com/ronindesign/ts3phpframework/wiki/Usage-Examples#9-create-a-simple-tsviewer-for-your-website):

```php
// load framework files
require_once("libraries/TeamSpeak3/TeamSpeak3.php");

// connect to local server, authenticate and spawn an object for the virtual server on port 9987
$ts3_VirtualServer = TeamSpeak3::factory("serverquery://username:password@127.0.0.1:10011/?server_port=9987");

// build and display HTML treeview using custom image paths (remote icons will be embedded using data URI sheme)
echo $ts3_VirtualServer->getViewer(new TeamSpeak3_Viewer_Html("images/viewericons/", "images/countryflags/", "data:image"));
```

Unfortunately, there's not much in way of examples of viewer options, I would advise checking the `TeamSpeak3_Viewer_Html` class.
Sorry there's not better documentation for this!

**Comment by svenpaulsen** [comment]
Basically, all you need to do is create your own custom class that implements `TeamSpeak3_Viewer_Interface`. The [fetchObject()](https://github.com/ronindesign/ts3phpframework/blob/master/lib/TeamSpeak3/Viewer/Interface.php) method is called once for every item in the server tree. Sorting and gathering the object information is done automatically by the framework.

Your code can then look like this:

```php
echo $server->getViewer(new YourCustomViewerClass($arg1, $arg2, $arg3));
```
