### ISSUE TITLE
URI option/flag clients_before_channels

### ISSUE THREAD

**Issue by Sebi94nbg** [planetteamspeak/ts3phpframework#112]
I don't like the doxygen documentation as I still can't find what I need. Due to this, I've created a wiki page for beginners: https://github.com/planetteamspeak/ts3phpframework/wiki/Factory-options-and-flags-explained

I'll create some more such pages to get started as easy as possible. :)

But... I didn't found out for what the option / flag `clients_before_channels` is. Could somebody please explain it? Thanks in advance!

**Comment by ronindesign** [comment]
Awesome, thanks for making a few pages. I think using the wiki is a great idea and I also dislike Doxygen format.
I've also made a few wiki pages (downstream as Sven has not confirmed using wiki):
https://github.com/ronindesign/ts3phpframework/wiki

Maybe we can create another doc site using something like [ReadTheDocs](https://readthedocs.org/)?
However, we'll probably want to stick with something that is mostly generated from code (aside from additional examples).
We want to be careful not to create another asset requiring additional upkeep.

Re: `clients_before_channels` - I believe this is sorting / display in the server tree.
If you check the code, you can see if the flag `clients_before_channels` is set, then `setLoadClientlistFirst(True)` is called.

For this we have in `TeamSpeak3_Node_Host::setLoadClientlistFirst()`:
> Sets the option to decide whether clients should be sorted before sub-channels to support the new TeamSpeak 3 Client display mode or not.
```php
$this->setStorage("_client_top", $first);
$this->sort_clients_channels = $first;
```

You should be able to use the HTML Viewer on a web page to visualize the effect this will have on sorting order when displaying users and sub-channels together.

**Comment by Sebi94nbg** [comment]
Thank you for the feedback - I've updated the wiki page! :)

I think the wiki page is enough for my purpose. I only want to write down a short, but more helpful get started tutorial. I don't want to explain every single function - I only want to explain, how you need to start in order to work with these functions. :)
