### ISSUE TITLE
Display server properties/information in table with key

### ISSUE THREAD

**Issue by Sebi94nbg** [planetteamspeak/ts3phpframework#113]
I would like to display a table with all virtualserver information:
```
$uri = "serverquery://".$serverquery_user.":".$serverquery_password."@".$serverquery_ip.":".$serverquery_port."/?server_port=$virtualserver_port#no_query_clients";

try {
	$TS3PHPFramework = new TeamSpeak3();
	$ts3_virtualserver = $TS3PHPFramework->factory("$uri");
} catch(TeamSpeak3_Exception $ex) {
	echo "An error occured!";
}
```

`$ts3_virtualserver` contains now following:
```
TeamSpeak3_Node_Server {#441 ▼
  #channelList: null
  #clientList: null
  #sgroupList: null
  #cgroupList: null
  #parent: TeamSpeak3_Node_Host {#423 ▶}
  #server: null
  #nodeId: 21
  #nodeList: null
  #nodeInfo: array:1 [▶]
  #storage: []
}
```

Using `$ts3_virtualserver->virtualserver_id` I'm able to access the correct value.

But when I try to loop through and return all values in a table, it's not working as it returns channel information.
```
foreach($ts3_virtualserver as $key => $value) {
        echo "$key => $value<br>";
}
```

I would expect an output like this:
```
virtualserver_unique_identifier => u++3gfOmYqWOOJZI+WGP7XBAcCM=
virtualserver_name => Test\sServer
virtualserver_welcomemessage => Welcome\sto\sTeamSpeak,\scheck\s[URL]www.teamspeak.com[\/URL]\sfor\slatest\sinformation
virtualserver_platform => Linux
...
```

But instead, I get an incrementing ID and the channel names:
```
0 => Default Channel
1 => Test Channel #1
2 => Test Channel #2
3 => Test Channel #3
...
```

I've already tried to convert the object into an array using `->toArray()`, but this returns only `null`. :(

**Comment by ronindesign** [comment]
Hmm, looks like factory calls `TeamSpeak3_Node_Host::serverGetByPort()`, which calls:
```php
  {
  $this->serverSelectByPort($port);
  return new TeamSpeak3_Node_Server($this, array("virtualserver_id" => $this->serverSelectedId()));
  }
```

Then, `TeamSpeak3_Node_Server::__constructor($hose, $nodeInfo, $index='virtualserver_id')`  doesn't seem to load any initial data from the server, it only instantiates the class and sets up basic structure waiting for your next action:
```php
{
  $this->parent = $host;
  $this->nodeInfo = $info;
 
  if(!array_key_exists($index, $this->nodeInfo))
  {
  throw new TeamSpeak3_Adapter_ServerQuery_Exception("invalid serverID", 0x400);
  }
 
  $this->nodeId = $this->nodeInfo[$index];
  }
```

So, it would seem`$this->nodeInfo` only contains a single `key:value` which was passed in by factory through class init.

I believe node info is acquired by inherited `TeamSpeak3_Node_Abstract::fetchNodeInfo()`, which is called in inherited `TeamSpeak3_Node_Server::getInfo()` [[ref](https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___abstract.html#ac60d6af1acba9d78d719d4b86e987c07)].

So I would try your code again, and modify to something similar:

```php
foreach($ts3_virtualserver->getInfo(TRUE) as $key => $value) {
        echo "$key => $value<br>";
}
```

```php
$ts3_virtualserver->getInfo(TRUE);
foreach($ts3_virtualserver as $key => $value) {
        echo "$key => $value<br>";
}
```
Once data has been initialized and nodeInfo / nodeList correctly filled with virtual server properties, then `toArray()` should work as expected since it does `return $this->nodeList;`.

**Comment by Sebi94nbg** [comment]
Perfect! Adding `->getInfo(TRUE)` did the trick, great. :)

Thanks a lot for the detailed explanation!

I've also added a second `true` parameter to convert some properties to human-readable values: `->getInfo(TRUE, TRUE)` :)

Btw: `VIRTUALSERVER_UPTIME` is converted, but `VIRTUALSERVER_CREATED` not. I think you forgot this value. Did you?

**Comment by Sebi94nbg** [comment]
Is there also a way to convert this variable? `CLIENT_CREATED`

Got this using this piece of code:
```
$uri = "serverquery://".$serverquery_user.":".$serverquery_password."@".$serverquery_ip.":".$serverquery_port."/?server_port=$virtualserver_port#no_query_clients";
$ts3_virtualserver = $TS3PHPFramework->factory("$uri");
$client_info = $ts3_virtualserver->request("clientinfo clid=".$ts3_virtualserver->whoamiGet('client_id'));
$client_variables = $client_info->toList();

foreach($client_variables as $key => $value) {
        echo "$key => $value<br>";
}
```

**Comment by ronindesign** [comment]
Confused about what you're asking? Are you saying `CLIENT_CREATED` property is not converted to "human readable format" like `VIRTUALSERVER_UPTIME` is?

`TeamSpeak3_Adapter_ServerQuery_Reply::toList()` doesn't have "convert" logic like `TeamSpeak3_Node_Abstract::getInfo()` has...
Sorry for confusion, not exactly sure what you're seeing vs. what you expect to see.

**Comment by Sebi94nbg** [comment]
Yes, it's not converted to human-readable. It also contains a unix-timestamp.

**Comment by ronindesign** [comment]
Yeah, the timestamp conversions only happen in a few, limited number of places, as it assumes a LOT of context regarding format of what is returned.

As you can see from other places in the code, usually conversion is done at the last possible step (i.e. before output) where the context is must specific:
From `libraries/TeamSpeak3/Viewer/Html.php`:
```php
295 | return "ID: " . $this->currObj->getId() . " \| Clients: " . $this->currObj->clientCount() . "/" . $this->currObj["virtualserver_maxclients"] . " \| Uptime: " . TeamSpeak3_Helper_Convert::seconds($this->currObj["virtualserver_uptime"]);
--
… |  
299 | return "ID: " . $this->currObj->getId() . " \| Codec: " . TeamSpeak3_Helper_Convert::codec($this->currObj["channel_codec"]) . " \| Quality: " . $this->currObj["channel_codec_quality"];
```
