### ISSUE TITLE
logView() Limit (Lines)

### ISSUE THREAD

**Issue by Sebi94nbg** [planetteamspeak/ts3phpframework#120]
Is there any reason, why `logView()` returns maximum 100 lines?

```
logView ( $lines = 30, $begin_pos = null, $reverse = null, $instance = TRUE )
```
Source: https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___host.html#ab05b137629980da8706d8335a2d4a7fc

I would like to decide, what's the maximum. In my case, I would like to use max. 500 lines for example to avoid fetching those lines every minute. I rather want to fetch those every half hour for example.

Is this limited by TeamSpeak or just a (personal) limit by the ts3phpframework?

**Comment by ronindesign** [comment]
100 lines is the maximum allowed returned by the `logview` command in the TeamSpeak 3 Query Client.

Ref: https://lethallhost.com.br/clientes/TeamSpeak%203%20Server%20Query%20Manual.pdf#page=18

We would also love to be able to change this as well.

I'm unsure your situation / use case, but one option might be to "pre-cache" the log, pulling all of it locally (where your framework is running) and then parse / pull as u need fit.

Either way, I'm still unsure why you cannot do your "500 lines every half hour" with the current implementation.
Just implement a stack (in memory or on disk) based on time (i.e. the last 30 min).
Then just "sync" your stack according to your parameters.
Shift older items off front of stack, add new (most recent) log entries to top of the stack.
This way you have running set of log entries for last 30 min, and only sync every 30 min.

In any case, let me know if you need further assistance on this.
Closing for now as there's nothing to implement here.

**Comment by Sebi94nbg** [comment]
Thanks for the feedback.

I'll now fetch the log every 30 minutes for every single virtual server and every 15 minutes for each instance.

Instance logView():

`logView ( 100, 0, true, true )`

Virtual server logView():

`logView ( 100, 0, true, false )`

This seems to work without loosing lines between each execution.

Otherwise (with `$reverse = false`) I get always the first 100 lines, which I already know. :)
