### ISSUE TITLE
TeamSpeak-Server 3.6.1 subscriber-Bug

### ISSUE THREAD

**Issue by thhan** [planetteamspeak/ts3phpframework#121]
Hello, I tried to use `\TeamSpeak3_Helper_Signal::getInstance()->subscribe()`, but I get everytime this error-message:
`[TeamSpeak3_Adapter_ServerQuery_Exception (524)]  
  client is flooding (please wait 1 seconds)`

Do you have an idea, why I get this message?

**Comment by ronindesign** [comment]
I'm not sure why those two would be connected, but I would definitely recommend disabling flood / white listing the bot.

Otherwise, I do know that some events / msgs from subscribe will return duplicate events, so maybe the extra event msg is triggering the flood notice?

**Comment by thhan** [comment]
How do i change the flood-value or disable it? Is this value new in TeamSpeak?

**Comment by ronindesign** [comment]
I'm referring to "Anti-Flood" settings via _Manage Virtual Server_ > _Anti-Flood (tab)_

![image](https://user-images.githubusercontent.com/1414401/55103267-5812a480-5085-11e9-8d5c-369bab681e6e.png)

**Comment by thhan** [comment]
The bot is whitelisted and i get this exeception again.
