### ISSUE TITLE
SSH2 lib

### ISSUE THREAD

**Issue by Dominik28111** [planetteamspeak/ts3phpframework#123]
Hello,

is it possible to switch to phpseclib instead of the php-ssh2 extension? In my opinion phpseclib is much better for options like timeout handling. If my instance is offline my webserver is throwing 504 Gateway-timeout. Not every person is able to change the php timeout settings in the ini file.

**Comment by ronindesign** [comment]
Seems like pretty minimal gain for switching an entire underlying extension.
However, I do also prefer `phpseclib`, maybe a configuration option could allow using one over the other.

Would this fit your need?
If so, we're more than willing to accept a PR for it.

Appreciate the feedback and ideas, thanks!

**Comment by Dominik28111** [comment]
A configuration option for this sounds good.

**Comment by ronindesign** [comment]
Not much happening on this project recently. Please feel free to submit PR for this feature and we'll gladly get it merged in. Closing for now.
