### ISSUE TITLE
Add User to Servergroup

### ISSUE THREAD

**Issue by MrCamby** [planetteamspeak/ts3phpframework#129]
How can I add an User to an specific Servergroup?

**Comment by realKitsune** [comment]
Hi, can you send some piece of code you've tried, or how do you want to add them exactly ?

**Comment by ronindesign** [comment]
With a quick search of the documentations using Google[[0](https://www.google.com/search?q=add+user+server+group+site%3Ahttps%3A%2F%2Fdocs.planetteamspeak.com%2Fts3%2Fphp%2Fframework%2F)], I found the class/method reference for TeamSpeak3_Node_Servergroup::clientAdd[[1](https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___servergroup.html#a8e42fbd723f1fba299029380b78a6bd0)]:

> **TeamSpeak3_Node_Servergroup::clientAdd( $cldbid )**
> 
> Adds a client to the server group specified.
> 
> _Please note that a client cannot be added to default groups or template groups._
> 
> **Parameters**
> integer	$cldbid	
> 
> **Returns**
> void

I also found the class/method reference for TeamSpeak3_Node_Server::serverGroupClientAdd[[2](https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___server.html#a0de946cd40ffece9e66793d8c9eb5530)]

> **serverGroupClientAdd( $sgid, $cldbid )**
> 
> Adds a client to the server group specified.
> 
> _Please note that a client cannot be added to default groups or template groups._
> 
> **Parameters**
> integer	$sgid
> integer	$cldbid
> 
> **Returns**
> void

Here are some examples:

```php
// load framework files
require_once("libraries/TeamSpeak3/TeamSpeak3.php");

// Example parameters
$sgid = 123;
$cldbid = 1337;
$clientName = "Test"

// connect to local server, authenticate and spawn an object for the virtual server on port 9987
$ts3_VirtualServer = TeamSpeak3::factory("serverquery://username:password@127.0.0.1:10011/?server_port=9987");

// Add server group with ID 123 to client with database ID 1337
$ts3_VirtualServer->serverGroupClientAdd($sgid, $cldbid)

// Add client with name "Test" to server group with ID 123
$ts3_VirtualServer->clientGetByName($clientName)->addServerGroup($sgid)

// Add client with database ID 1337 to server group with ID 123
$ts3_VirtualServer->serverGroupGetById($sgid)->addClient($cldbid)
```

[0] Searched on Google with query `add user server group site:https://docs.planetteamspeak.com/ts3/php/framework/`
[1] https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___servergroup.html#a8e42fbd723f1fba299029380b78a6bd0
[2] https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___server.html#a0de946cd40ffece9e66793d8c9eb5530

**Comment by DerMatteo** [comment]
Thank you!! I searched so long for the solution!!
