### ISSUE TITLE
TeamSpeak3_Viewer_Html: str_pad(): Padding string cannot be empty

### ISSUE THREAD

**Issue by Sebi94nbg** [planetteamspeak/ts3phpframework#136]
I have the problem, that one of my TeamSpeak 3 servers can't be displayed using the standard TS3 Viewer feature of this library.

I've double-checked the used URI and it's correct. The virtualserver ID is correct, exists and matches the respective TS3 server.

When I change the virtualserver id statically to any other existing virtualserver, the TS3 viewer is working as expected.

This is the stacktrace:

![image](https://user-images.githubusercontent.com/5154682/71783777-d6747d80-2feb-11ea-8a4f-38f095905834.png)

I'm confused why the result of the factory is always empty, because TeamSpeak does not log any errors - only the information, that the query successfully connected to this specific virtualserver id.

This is the result of the factory URI `"serverquery://serveradmin:<password>@<serverquery_ip>:10022/?ssh=1&use_offline_as_virtual&server_id=850#no_query_clients"`:

```php
$uri = "serverquery://serveradmin:<password>@<serverquery_ip>:10022/?ssh=1&use_offline_as_virtual&server_id=850#no_query_clients";

$TS3PHPFramework = new TeamSpeak3();

try {
    $ts3virtualserver = $TS3PHPFramework ->factory("$uri");
} catch (TeamSpeak3_Exception $ex) {
    return false;
}

return $ts3virtualserver;
```

![image](https://user-images.githubusercontent.com/5154682/71783809-41be4f80-2fec-11ea-8eed-832fb3a362af.png)

What's the issue here and how can I fix this?

**Comment by Sebi94nbg** [comment]
@ronindesign @svenpaulsen any idea? This issue causes, that the TS3 Viewer does not load and thus the entire page can not be displayed.

Is there any way to try-catch errors in order to show something like "could not render TS3 Viewer" in case of any issues?

**Comment by svenpaulsen** [comment]
I guess this happens when people create repeating spacers without a display name to make use of the TS5 channel banners. Please re-test with the current master.
