### ISSUE TITLE
Invalid client id

### ISSUE THREAD

**Issue by EatTobiYT** [planetteamspeak/ts3phpframework#138]
Hello,
if I try to “create” a client using the unique id, I always get the error “invalid client Id”. The client is online.

```php
$uri = "serverquery://<queryuser>:<querypassword>@<ip>:<queryport>/?server_port=<port>&nickname=Test";
TeamSpeak3::init();
$ts3server = TeamSpeak3::factory($uri);
$client = $ts3server->clientGetByUid("XXXXXXXXXXXXXXXXXXX=");
$client->poke('testmessage');
```

Greetings
Tobias

**Comment by svenpaulsen** [comment]
I'm still unable to reproduce this. I assume you're using the official TeamSpeak Server so please make sure the UID is correct, the client is connected to the server and is in a channel the ServerQuery client is allowed to subscribe.

**Comment by EatTobiYT** [comment]
Can you please tell me with which version you tested it and send me your test code? I get this error all the time and can't fix it. I just can't find the error.

**Comment by svenpaulsen** [comment]
Latest TeamSpeak Server release using your code snippet...
