### ISSUE TITLE
Get client infos from database

### ISSUE THREAD

**Issue by MitoCodeGithub** [planetteamspeak/ts3phpframework#139]
Hello,

I can change the description of an offline client...
To change the description I do this:
`$ts3server->clientModifyDb($cldbid, array("client_description" => "HelloWorld"));`

But how can I get the description while the client is offline? I want to do the same with the client's avatar.

Many thanks,
Mito

**Comment by Newcomer1989** [comment]
Via the serverquery your can use the command `clientdbinfo cldbid=XXX`.
Your answer will be looks like:
```
client_unique_identifier=xrTKhT\/HDl4ea0WoFDQH2zOpmKg=
client_nickname=Newcomer1989
client_database_id=7775
client_created=722870625
client_lastconnected=1582448034
client_totalconnections=3976
client_flag_avatar
client_description=Nichts\sauf\sder\sWelt\sist\sso\sgut\sverteilt\sals\sder\sVerstand.\sDenn\sjeder\sist\süberzeugt,\sgenug\sdavon\szu\shaben.
client_month_bytes_uploaded=4668
client_month_bytes_downloaded=757220
client_total_bytes_uploaded=16662997
client_total_bytes_downloaded=349147676873
client_base64HashClientUID=mglemkifdpmhaofoboglefkibedeahnlddkjjiki
client_lastip=87.187.29.176
```

On the ts3phpframework use something like this -> simplified code example:

```
$cldbid = '7775';
$clientinfo = $ts3server->clientInfoDb($cldbid);
echo $clientinfo['client_description'];
```

**Comment by MitoCodeGithub** [comment]
Many thanks! It works! Very simple...🤦‍♂️
Do you know if I can modify the client's avatar (delete and upload)? And how can I get the client's avatar? What does **client_flag_avatar** mean?

Thank you,
Mito

**Comment by svenpaulsen** [comment]
`client_flag_avatar` holds the MD5 hash of the avatar file so you're able to verify that a users avatar has changed on the server when you're caching things.

Uploading avatars for other users is not possible. Deleting the avatar can be done by manually deleting the appropriate file from channel ID 0.
