### ISSUE TITLE
Inconsistent response from serverCreate

### ISSUE THREAD

**Issue by vaunus** [planetteamspeak/ts3phpframework#143]
I have noticed that the `serverCreate` function within the framework produces an inconsistent response and fails to directly return the `sid`, `virtualserver_port` and `token` on some occasions. From my testing, this appears to be something to do with the TeamSpeak server itself so perhaps this also needs to be reported to the TeamSpeak team and it is not a ts3phpframework issue at all. I just thought you should be aware as it has been an intermittent issue I've been trying to track down for the past 6 months when customers order servers from us, so I am sure it is affecting some other users of this framework.

It appears the issue is due to the information header that is printed out when a server is created. Sometimes this header forms part of the response within the framework, and other times it does not. 

The header I am referring to is this:
```
servercreate virtualserver_name=Test1 virtualserver_maxclients=2

------------------------------------------------------------------
                       I M P O R T A N T
------------------------------------------------------------------
      ServerAdmin privilege key created, please use it to gain
      serveradmin rights for your virtualserver. please
      also check the doc/privilegekey_guide.txt for details.

       token=Cu1dX2jci5dCgBIPFiy8sVcu0txxxxxxxxxxxxxxxxxx
------------------------------------------------------------------

sid=71 token=Cu1dX2jci5dCgBIPFiy8sVcu0txxxxxxxxxxxxxxxxxx virtualserver_port=10003
error id=0 msg=ok
```

I wrote a script to test this which simply creates a server and dumps out the response. Please see below for an essence of how that script looks:
```
$params = [
    'virtualserver_name' => 'Test',
    'virtualserver_maxclients' => 2
]

$result = $this->getConnection()->serverCreate($params);

var_dump($result);
```

The result appears as follows when this works correctly:
```
~ php test.php
array(3) {
  ["sid"]=>
  int(67)
  ["token"]=>
  object(TeamSpeak3_Helper_String)#22 (2) {
    ["string":protected]=>
    string(40) "RVTzXssBOUHdeTks9rmgMWxxxxxxxxxxxxxxxxx"
    ["position":protected]=>
    int(0)
  }
  ["virtualserver_port"]=>
  int(9999)
}
```

And as follows when the header is captured as part of the response:
```
~ php test.php
array(9) {
  [1]=>
  array(1) {
    ["------------------------------------------------------------------"]=>
    NULL
  }
  [2]=>
  array(8) {
    ["I"]=>
    NULL
    ["M"]=>
    NULL
    ["P"]=>
    NULL
    ["O"]=>
    NULL
    ["R"]=>
    NULL
    ["T"]=>
    NULL
    ["A"]=>
    NULL
    ["N"]=>
    NULL
  }
  [3]=>
  array(1) {
    ["------------------------------------------------------------------"]=>
    NULL
  }
  [4]=>
  array(9) {
    ["ServerAdmin"]=>
    NULL
    ["privilege"]=>
    NULL
    ["key"]=>
    NULL
    ["created,"]=>
    NULL
    ["please"]=>
    NULL
    ["use"]=>
    NULL
    ["it"]=>
    NULL
    ["to"]=>
    NULL
    ["gain"]=>
    NULL
  }
  [5]=>
  array(6) {
    ["serveradmin"]=>
    NULL
    ["rights"]=>
    NULL
    ["for"]=>
    NULL
    ["your"]=>
    NULL
    ["virtualserver."]=>
    NULL
    ["please"]=>
    NULL
  }
  [6]=>
  array(6) {
    ["also"]=>
    NULL
    ["check"]=>
    NULL
    ["the"]=>
    NULL
    ["doc/privilegekey_guide.txt"]=>
    NULL
    ["for"]=>
    NULL
    ["details."]=>
    NULL
  }
  [8]=>
  array(1) {
    ["token"]=>
    object(TeamSpeak3_Helper_String)#26 (2) {
      ["string":protected]=>
      string(40) "EWvGQampjoZawSdhFfRTaL6Yxxxxxxxxxxxxxx"
      ["position":protected]=>
      int(0)
    }
  }
  [9]=>
  array(1) {
    ["------------------------------------------------------------------"]=>
    NULL
  }
  [11]=>
  array(3) {
    ["sid"]=>
    int(68)
    ["token"]=>
    object(TeamSpeak3_Helper_String)#17 (2) {
      ["string":protected]=>
      string(40) "EWvGQampjoZawSdhFfRTaL6Yxxxxxxxxxxxxxx"
      ["position":protected]=>
      int(0)
    }
    ["virtualserver_port"]=>
    int(10000)
  }
}
```

I have noticed that some servers seem to get themselves into a state where they will consistently return the second response. I tested this while writing this issue and this happened 10 times in a row when running my test script. I restarted the server and the correct expected response appears to be consistent now.

**Comment by ronindesign** [comment]
Possibly looks like something unexpected is happening during parsing response. Thanks for the thorough report, I'll look into this and see if I can diagnose what's causing the issue.

**Comment by svenpaulsen** [comment]
The output you've pasted (_"ServerAdmin privilege key created, ..."_) should not be sent via ServerQuery. I'm unable to reproduce this on my end. Which version of the server are you using?

**Comment by vaunus** [comment]
The server version I ran the above tests on is `3.12.0` on Linux. However, I've seen this intermittent issue with creating servers for about 6-9 months now so I expect the issue has been around in older versions. I have just tested on the server I had run these tests on a few days ago and it is working again at the moment, whereas when I last tested it was consistently returning that extra header data. I agree this seems to be unexpected behaviour on the TeamSpeak server side so I will raise the issue with the team there.

**Comment by svenpaulsen** [comment]
Which type of ServerQuery are you using (Classic or SSH)?

**Comment by vaunus** [comment]
Classic

**Comment by svenpaulsen** [comment]
And just to be sure... we're talking about a regular, unmodified TeamSpeak Server right? :-P

**Comment by vaunus** [comment]
Yes, these are unmodified servers.

**Comment by svenpaulsen** [comment]
Weird... sorry, but I have no idea why this would be sent to a ServerQuery client.

Unfortunately, I no longer have access to the server code so I can't investigate, but if I remember correctly, the initial privilege key for a server is written into the logs and to [std::cerr](https://en.cppreference.com/w/cpp/io/cerr).

Anyway... this is not a framework issue, but I'd recommend a simple workaround, where you check the return value of `serverCreate()` and handle the inconsistent server output. Something like this:

```
$result = $ts3->serverCreate($properties);

if (!isset($result["sid"])) {
    $result = end($result);
}
```

**Comment by vaunus** [comment]
Yeah no problem. I've already done something similar to the workaround you suggested above.

**Comment by svenpaulsen** [comment]
Thanks for the feedback! Please feel free to open a new issue if you have any other questions.
