### ISSUE TITLE
Deprecated feature in PHP 7.4

### ISSUE THREAD

**Issue by AyrA** [planetteamspeak/ts3phpframework#148]
Curly braces for indexes are deprecated as of PHP 7.4 (Released 28 Nov 2019): https://wiki.php.net/rfc/deprecate_curly_braces_array_access

Type | Exception
-- | --
Message | [String.php:890] Array and string offset access syntax with curly braces is deprecated
Code | 0x00002000
Trace | lib.php (Line: 694)
Trace | TeamSpeak3.php(452) err(integer,string,string,integer,array)
Trace | TeamSpeak3.php(452) include_once()
Trace | TeamSpeak3.php(507) loadClass(string)
Trace | <unknown>(?) autoload(string)
Trace | Uri.php(218) spl_autoload_call(string)
Trace | TeamSpeak3.php(322) getScheme()

These braces need replacement with square brackets. A migration script is available: https://gist.github.com/theodorejb/763b83a43522b0fc1755a537663b1863

**Comment by Sebi94nbg** [comment]
All deprecated curly braces should be replaced with square braces.
