### ISSUE TITLE
Adapter Instances Result In Uncollected Cyclic References

### ISSUE THREAD

**Issue by ronindesign** [planetteamspeak/ts3phpframework#15]
See discussion in #14 regarding initial scenario where instantiating instance of `TeamSpeak3_Adapter_FileTransfer` results in cyclic references which are never garbage collected since the 'root buffer' is never filled. This results in dangling TCP socket connections stuck in CLOSE_WAIT status since the adapter's `__destruct` method is never called by garbage collection.

The general case is that instantiating any instance of a `TeamSpeak3_Adapter_Abstract` results in cyclic references. For example, to get the number of garbage cyclic references for an instance:
```php
$ts3 = TeamSpeak3::factory("serverquery://serveradmin:XXXXXXXX@255.255.255.255:10011/");
unset($ts3);
echo gc_collect_cycles();

OUTPUT:
17
```
The resulting number of cyclic references for this instance of `TeamSpeak3_Adapter_ServerQuery` were `17`.

Should instantiation of adapters be handled differently as to not create cyclic references?

Should the framework be handling the destruct process differently?

Should recursive or cyclic references be removed manually somehow?

**Comment by svenpaulsen** [comment]
Fixed with pull request #16.
