### ISSUE TITLE
Add MIT or LGPL license

### ISSUE THREAD

**Issue by sail0r89** [planetteamspeak/ts3phpframework#150]
I have seen that this library is licensed under GPL without any linking exception. This means that any project which includes this library needs to be GPL licensed too. Is this really what is intended by the original author of this library? I would recommend to dual license the library under LGPL or MIT to avoid license issues with other projects.

I have found several other projects at github which are violating GPL because they rely on this library and have a non-GPL license itself:

- https://github.com/Najsr/Twitch-TS3-Subscriber-bridge/blob/master/LICENSE
- https://github.com/kallefrombosnia/TS3BackupScript
- https://github.com/xaronnn/TeamSpeak3-Twitch-Followers
- https://github.com/xTeJk/betaspeak
- https://github.com/minecraft-skyrealm/NamelessMC
- https://github.com/derrobin154/tsgroupassigner

Based on https://github.com/planetteamspeak/ts3phpframework/graphs/contributors it may be possible to contact all 12 contributors to agree on the additional license. The most important persons from my understanding are @svenpaulsen and @ronindesign as this would allow version 1.1.24 to be licensed under another license and would allow most basic functions without GPL violation.

**Comment by ronindesign** [comment]
Thanks for the thoughtful comment and the work in compiling the list below,
really appreciate it!

As an FYI, @svenpaulsen holds exclusive licensing rights, so this would
have to be his call. I can't speak to the reasoning behind his choice in
licensing, but I personally am in favor of the more permissible MIT
license, or maybe GPLv2 (if I remember correctly) to include credit without
the copyleft requirement.

Thanks again for this contribution, it's definitely an important issue to
examine.

**Comment by sail0r89** [comment]
@svenpaulsen could you please review this request?

**Comment by Sebi94nbg** [comment]
@svenpaulsen Have you thought about this in the meantime?

**Comment by svenpaulsen** [comment]
I'll change the license from GPL to MIT later this week.

**Comment by svenpaulsen** [comment]
Sorry guys... I'm super busy over here and didn't have time to tackle this so far. If someone could submit a pull request and change the license to MIT, I'm happy to merge it asap.

**Comment by ronindesign** [comment]
#197 has changed this projects license from GPL to MIT as per Sven's approval in https://github.com/planetteamspeak/ts3phpframework/issues/150#issuecomment-1481562929
