### ISSUE TITLE
PHP 8.0 - Deprecated required parameters following optional parameter

### ISSUE THREAD

**Issue by Newcomer1989** [planetteamspeak/ts3phpframework#151]
I am currently testing the PHP 8.0 RC 1 with a custom script.

The framework seems to be working fine with it. But I am using only a few functions of it.

One thing, which I noticed is the new check on functions. Is there a required parameter following an optional parameter, it returns an info message. It's no big deal. I only want to report it. ([more information](https://php.watch/versions/8.0/deprecate-required-param-after-optional))

Concerned functions:
https://github.com/planetteamspeak/ts3phpframework/blob/d629e767acf9d21056b3588e909443177d2bac47/libraries/TeamSpeak3/Node/Server.php#L2021

https://github.com/planetteamspeak/ts3phpframework/blob/d629e767acf9d21056b3588e909443177d2bac47/libraries/TeamSpeak3/Node/Server.php#L2036

Example (custom) error output:
```
2020-10-09 09:50:41.805911   INFO      8192: Required parameter $id1 follows optional parameter $type on line 2021 in /var/www/tsn/ranksystem_dev/libs/ts3_lib/Node/Server.php
2020-10-09 09:50:41.805817   INFO      8192: Required parameter $id1 follows optional parameter $type on line 2036 in /var/www/tsn/ranksystem_dev/libs/ts3_lib/Node/Server.php
```

An easy fix would be to set the $id1 as optional parameter like
`  public function privilegeKeyCreate($type = TeamSpeak3::TOKEN_SERVERGROUP, $id1 = 0, $id2 = 0, $description = null, $customset = null)`

This will run into an TS3 error, when the $id1 is not given by the third party script, since it is the groupID of the TS3 query function `tokenadd`.
As a second possibility I see the option to change the order of the parameters. It's your decision. ;-)

**Comment by ronindesign** [comment]
Thanks for the heads up and pointing this out, we'll definitely consider this.

**Comment by Domenikus** [comment]
PHP 8.1 is released since a while. Would be nice to have updated dependencies.
