### ISSUE TITLE
Unparenthesized `a ? b : c ? d : e` is deprecated

### ISSUE THREAD

**Issue by iatoz** [planetteamspeak/ts3phpframework#154]
I got the error, In php7.4.10
```
exception: "ErrorException"
file: "***\planetteamspeak\ts3-php-framework\libraries\TeamSpeak3\Viewer\Json.php"
line: 389
message: "Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`"
```

the line 389:
`$props->icon     = $this->currObj->isSpacer() ? 0 : $this->currObj->channel_icon_id < 0 ? pow(2, 32)-($this->currObj->channel_icon_id*-1) : $this->currObj->channel_icon_id;`
change to
`$props->icon     = ($this->currObj->isSpacer() ? 0 : $this->currObj->channel_icon_id < 0) ? pow(2, 32)-($this->currObj->channel_icon_id*-1) : $this->currObj->channel_icon_id;`

then the bug is fixed.

**Comment by ronindesign** [comment]
Thank you for tracking down the issue. Your fix has been committed. Please let me know if you continue to have trouble. Otherwise, I'll assume this fixed!

Commit: 8ee256d9aab0a7b8466fd00bbd445a7278478890
