### ISSUE TITLE
PHP 8.0 Fatal error: Array and string offset access syntax with curly braces is no longer supported in \libraries\TeamSpeak3\Helper\String.php on line 890

### ISSUE THREAD

**Issue by T-Kalweit** [planetteamspeak/ts3phpframework#159]
Hi,

I'm using Joomla 3.9.25, Apache Apache/2.4.46 (Win64) and PHP8.0.3, on Windows Server 2019.
If I use the teamspeak module in a artikel like {loadmoduleid 110} I get an Error.

> Fatal error: Array and string offset access syntax with curly braces is no longer supported in \libraries\TeamSpeak3\Helper\String.php on line 890

**Comment by CodazziS** [comment]
Compatibility problem seem solved in the master branch. 
Just need a new release. (You can force composer to get master branch instead release tag, for testing)

**Comment by naitsirch** [comment]
@svenpaulsen or @ronindesign Could you create a new release?

**Comment by ronindesign** [comment]
@naitsirch release v1.1.35 has been created. This issue is now resolved.

**Comment by naitsirch** [comment]
Thanks for your fast reaction :-)

**Comment by naitsirch** [comment]
@svenpaulsen The release seems not being auto updated on packagist.org. Are you able to do the update?
