### ISSUE TITLE
Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by dwwe2017** [planetteamspeak/ts3phpframework#186]
I have a lot of lines in my error log with the following message

```text
[error] (8) Trying to access array offset on value of type int: ../vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Node/Host.php 613
```

https://github.com/planetteamspeak/ts3phpframework/blob/831ec5016162cc02ca45757cbf01c45911fc7591/libraries/TeamSpeak3/Node/Host.php#L613

**Comment by Sebi94nbg** [comment]
@dwwe2017 can you please provide some more information?

- Which version of this library do you use?
- How does your code look like, which causes this issue?

**Comment by dwwe2017** [comment]
Hi, I'm using the latest version of the framework (1.1.35) and I'm using it as intended. The framework is currently operated with PHP 7.4.

I would suggest to include a check if the array keys exist.

**Comment by ronindesign** [comment]
This should now be resolved, please reopen if not.
