### ISSUE TITLE
PHP 7.1 Incompatibility with unset($this)

### ISSUE THREAD

**Issue by venyii** [planetteamspeak/ts3phpframework#19]
Unsetting `$this` is not allowed anymore in PHP 7.1 ([RFC](https://wiki.php.net/rfc/this_var)). See https://3v4l.org/pNQvK

The following classes are affected:
* `libraries/TeamSpeak3/Node/Servergroup.php`
* `libraries/TeamSpeak3/Node/Channelgroup.php`
* `libraries/TeamSpeak3/Node/Channel.php`
* `libraries/TeamSpeak3/Node/Server.php`

I could provide a PR removing these lines if you like, unless you have another solution.

Thanks!

**Comment by hvanmegen** [comment]
instead of unsetting it, can't you just destroy the object?
