### ISSUE TITLE
Implicit conversion from float 1678378651.114998 to int loses precision 

### ISSUE THREAD

**Issue by Grepher76380** [planetteamspeak/ts3phpframework#193]
Hello

test dev-dev error : Implicit conversion from float 1678378651.114998 to int loses precision 

FCPATH/vendor/planetteamspeak/ts3-php-framework/src/Helper/Profiler/Timer.php at line 93

 86         if ($this->isRunning()) {
 87             return;
 88         }
 89 
 90         $this->data["realmem_start"] = memory_get_usage(true);
 91         $this->data["emalloc_start"] = memory_get_usage();
 92 
 93         $this->started = microtime(true);
 94         $this->running = true;
 95     }

php version : 8.1.16 AND 8.0.28 
Use:  codeigniter4

**Comment by Sebi94nbg** [comment]
I've already opened a pull request to fix it: https://github.com/planetteamspeak/ts3phpframework/pull/188

**Comment by Sebi94nbg** [comment]
This issue has been fixed with the above mentioned pull request. :)
