### ISSUE TITLE
FCPATH/vendor/planetteamspeak/ts3-php-framework/src/Helper/Convert.php at line 94

### ISSUE THREAD

**Issue by Grepher76380** [planetteamspeak/ts3phpframework#194]
$data['virtualserver_uptime'] = Convert::seconds($ts3->virtualserver_uptime);

error : Implicit conversion from float 144.08388888888888 to int loses precision 

FCPATH/vendor/planetteamspeak/ts3-php-framework/src/Helper/Convert.php at line 94

 87      */
 88     public static function seconds(int $seconds, bool $is_ms = false, string $format = "%dD %02d:%02d:%02d"): string
 89     {
 90         if ($is_ms) {
 91             $seconds = $seconds / 1000;
 92         }
 93 
 94         return sprintf($format, $seconds / 60 / 60 / 24, ($seconds / 60 / 60) % 24, ($seconds / 60) % 60, $seconds % 60);
 95     }
 96 
 97     /**
 98      * Converts a given codec ID to a human-readable name.
 99      *
100      * @param integer $codec
101      * @return string

**Comment by Sebbo94BY** [comment]
Fixed by PR #202.
