### ISSUE TITLE
Suppoort fpr php 8.1+

### ISSUE THREAD

**Issue by horvan** [planetteamspeak/ts3phpframework#196]
since PHP 7.4 is EOL now it would be great, if that codebase could support php8.1 real soon.

**Comment by Sebi94nbg** [comment]
The pre-release [1.2.0](https://github.com/planetteamspeak/ts3phpframework/releases/tag/1.2.0) already supports PHP 8.0, 8.1 and 8.2.

Also see the [dev branch](https://github.com/planetteamspeak/ts3phpframework/tree/dev) for more changes and information.
