### ISSUE TITLE
PHP 8.2: Function utf8_encode() is deprecated

### ISSUE THREAD

**Issue by Sebi94nbg** [planetteamspeak/ts3phpframework#198]
> Function utf8_encode() is deprecated in src/Helper/StringHelper.php on line 472

**Comment by MatthiasHeinz** [comment]
A possible fix for `Function utf8_encode() is deprecated in src/Helper/StringHelper.php on line 472` might be `$this->string = mb_convert_encoding($this->string, 'UTF-8', mb_list_encodings());`.

**Comment by Sebi94nbg** [comment]
I've now merged my suggestion since the PHPUnit tests were successful and nobody complained about it. :)

**Comment by MatthiasHeinz** [comment]
Thanks so much for your work; I'm gonna test this when I get a chance (probably next week) and report back in case of any further issues.
