### ISSUE TITLE
How to get Node\Host instance?

### ISSUE THREAD

**Issue by Wruczek** [planetteamspeak/ts3phpframework#215]
`TeamSpeak3::factory` returns a `Node\Server` instance, how can I get a `Node\Host` instance?
On version `1.1` it was possible to create it by not specifying a `server_port` in `TeamSpeak3::factory`.
I'm using TeamSpeak 3 PHP Framework 1.2.1 on PHP 8.2.12.

**Comment by Sebbo94BY** [comment]
Fixed - only the return types were not correct. Added the additional and missing ones.
