### ISSUE TITLE
Doubled onEvent output

### ISSUE THREAD

**Issue by Arajdon** [planetteamspeak/ts3phpframework#22]
Every "onEvent" action is beeing executed twice.

This happens when I switch between channels:
```
[SIG]   received notification clientmoved
        ctid=50 reasonid=0 clid=21
[SIG]   received notification clientmoved
        ctid=50 reasonid=0 clid=21
[SIG]   received notification clientmoved
        ctid=58 reasonid=0 clid=21
[SIG]   received notification clientmoved
        ctid=58 reasonid=0 clid=21
[SIG]   received notification clientmoved
        ctid=71 reasonid=0 clid=21
[SIG]   received notification clientmoved
        ctid=71 reasonid=0 clid=21
```

I guess TeamSpeak won't fix this bug.
http://forum.teamspeak.com/threads/91989-Getting-notifyclientmoved-events-twice

Any ideas on fixing or bypassing this error?

**Comment by svenpaulsen** [comment]
As I already stated in the thread you referred to, this is a server-side issue. I guess the only thing you can do is maintain your own client/channel list in the background and ignore events when you're already up-to-date.
