### ISSUE TITLE
serverqueryWaitTimeout no longer called

### ISSUE THREAD

**Issue by I-MrFixIt-I** [planetteamspeak/ts3phpframework#23]
So, the serverqueryWaitTimeout event is no longer called.
This is caused my this change: https://github.com/planetteamspeak/ts3phpframework/commit/33616381cd8f5b8442b8c7988ec9e88dca9dae19

Undo it and everything worked fine for me again :)

**Comment by JABirchall** [comment]
We had a simular issue here: https://github.com/fkubis/teamspeak-php-framework/issues/8

When adding the patch serverqueryWaitTimeout was called as unknownWaitTimeout

**Comment by ronindesign** [comment]
That makes sense as it follows from the logic, since 3361638 changed the object to a string from an actual object ref, there is most likely another lookup happening that was not refactored correctly.

I'll test this tonight.

**Comment by JABirchall** [comment]
I don't know why that change was made, It does nothing but break the framework. not only can it not refactor the adapter, But when to listen for unknownWaitTimeout, the adapter parameter is the adapter class name, when it should be an instance of the adapter.

**Comment by I-MrFixIt-I** [comment]
@JABirchall 
I asked the same, @ronindesign wrote the following: "This was to correct cyclic references."
As I had the same problem as you I decided you fork this project and made the appropriate changes.
You can download it from here: https://github.com/I-MrFixIt-I/ts3phpframework
And here the changes I made: https://github.com/I-MrFixIt-I/ts3phpframework/commit/290f3bc0c9f281b44dc9847b747913752e59f183

**Comment by JABirchall** [comment]
@I-MrFixIt-I Then why not make a https://github.com/planetteamspeak/ts3phpframework/pulls

**Comment by I-MrFixIt-I** [comment]
@JABirchall Because @svenpaulsen wrote https://github.com/planetteamspeak/ts3phpframework/commit/33616381cd8f5b8442b8c7988ec9e88dca9dae19 that he will update and fix this (without removing the cyclic refenrece stuff). Which is actually more then a week ago ^^
But I can make a pull request if you feel better then ;)

**Comment by ronindesign** [comment]
@JABirchall I'm not sure what you mean.

The refactoring was to replace the cyclic references that stop garbage collection, and break proper socket clean-up else where.

The refactoring does work, as the reference is never used as an object to access anything. Instead it is only used as a string via lookup, so replacing _(string) get_class($adapter)_ with _(string) 'serverquery'_ has the same result.

As @I-MrFixIt-I mentions, @svenpaulsen is working on a proper fix that will handle all related issues, this is also why I've not made it a priority as reverting this will simply offload the bug to another place in the code...

**Comment by ronindesign** [comment]
3361638 was reverted. `serverqueryWaitTimeout` event is now working as expected again. Please reopen if there is still an issue.
