### ISSUE TITLE
Filter ServerQuery client from client list

### ISSUE THREAD

**Issue by NicholasJohn16** [planetteamspeak/ts3phpframework#24]
Is there an option or filter that can be passed into clientList() that will exclude the ServerQuery client? I've tried checking all the documentation for this framework and ServerQuery, but can't find anything. How does the included viewer exclude the ServerQuery client? 

Thank you for any assistance.

**Comment by Najsr** [comment]
`$clients = $ts3_VirtualServer->clientList();
foreach($clients as $client){
if($client['client_type']) continue; //This will exclude server query clients
}`

**Comment by ronindesign** [comment]
You could also pass in the _no_query_clients_ flag in the factory:

```php
serverquery://127.0.0.1:10011/?server_port=9987&channel_id=1#no_query_clients
```

[[ref](https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3.html#aa0f699eba7225b3a95a99f80b14e73b3)]

**Comment by NicholasJohn16** [comment]
I'm trying to use the `no_query_clients` flag, but it doesn't seem to work. Does a channel_id have to be included for it to work? BTW, is there any documentation for what those options and filters do?

**Comment by ronindesign** [comment]
You shouldn't need _channel_id_, see my [ref] link for documentation on the factory. There are examples and list of flags.
