### ISSUE TITLE
Uri parser is broken when password contains slash

### ISSUE THREAD

**Issue by Nothing4You** [planetteamspeak/ts3phpframework#26]
Hey there,

[this regex](https://github.com/planetteamspeak/ts3phpframework/blob/master/libraries/TeamSpeak3/Helper/Uri.php#L145) doesn't work when the password contains a slash.

Example:
`//serveradmin:justsome/randompass@127.0.0.1:10011/?server_port=9987`
Results in `$matches[4]` (supposedly path) being `randompass@127.0.0.1:10011/`.

**Comment by svenpaulsen** [comment]
There are indeed special cases when this is not working. I'd recommend doing something like this when you don't know the username and/or password that's going to be used.

```php
$ts3 = TeamSpeak3::factory("serverquery://host:port");

$ts3->login($username, $password);
```
