### ISSUE TITLE
HTTP ERROR 500 php7:error

### ISSUE THREAD

**Issue by jelidi** [planetteamspeak/ts3phpframework#27]
[Wed Jan 25 14:01:43.616384 2017] [php7:error] [pid 15462] [client ** ** ** ** **] PHP Fatal error:  Cannot unset $this in /var/www/html/ts/lib/ts3phpframework/libraries/TeamSpeak3/Node/Server.php on line 2272

**Comment by bykidi** [comment]
this was fixed in #19
