### ISSUE TITLE
clientGetById() triggers "invalid clientID" if client connects 2 times

### ISSUE THREAD

**Issue by Arajdon** [planetteamspeak/ts3phpframework#28]
```
$eventData = $event->getData();
$ts3->clientGetById($eventData['clid']);
```
clientGetById() triggers an "invalid clientID" if the client connects 2 times with the same identity to the server. But the clientID stays unique.

If there is for example another identity which connects in between, no error is triggered.

```
LIB Version: 1.1.24
Server: 3.0.13.4 on Linux
```

Any workaround or fix for this?

KR.

**Comment by Najsr** [comment]
Which event are you using? This will definitely not work on notifyclientleft for example.

**Comment by Arajdon** [comment]
I am using "cliententerview". It is logical that nothing can be found if a user is not online. But in this case both clients with the same identity are online.

Some background: If the user joins the server, i want to send him a message.

**Comment by Najsr** [comment]
Well, take a look at https://github.com/JABirchall/NimdaTS3. I personally use it and it's pretty easy to set up an plugin for it.

**Comment by Arajdon** [comment]
Using another system/bot/framework/whatever won't fix this problem nor speed up my work. Anyway thanks for the tip.

**Comment by JABirchall** [comment]
You need to refresh the client list by invoking $ts->clientListReset();
