### ISSUE TITLE
insufficient client permissions (failed on banlist 209/0xD1)

### ISSUE THREAD

**Issue by JanneSaukkio** [planetteamspeak/ts3phpframework#3]
Hi!

I'm trying to get my server's banlist with this framework but it keeps making this exception 

> PHP Fatal error:  Uncaught exception 'TeamSpeak3_Adapter_ServerQuery_Exception' with message 'insufficient client permissions (failed on banlist 209/0xD1)' in  .../libraries/TeamSpeak3/Adapter/ServerQuery/Reply.php:319

I have set permission for **Guest Server Query** and **Admin Server Query** to b_client_ban_list. Oddly enough getting clients from database works...

Code below is almost a direct copy from documentation's example

```
<?php

require "libraries/TeamSpeak3/TeamSpeak3.php";

$ts3 = TeamSpeak3::factory("serverquery://user:pass@127.0.0.1:10011/?server_port=9987");

$list = $ts3->banList();

echo "<pre>".print_r($list, true)."</pre>";

?>
```

**Comment by svenpaulsen** [comment]
Obviously, your ServerQuery client does not have the permission to view the ban list. Try using the **selfPermCheck()** method to verify your permissions.

`TeamSpeak3::dump( $ts3->selfPermCheck("b_client_ban_list") );`

Please refer to the official [TeamSpeak](http://forum.teamspeak.com) community forums as this is not really an issue with the TS3 PHP Framework.
