### ISSUE TITLE
Interacting with TsViewer

### ISSUE THREAD

**Issue by marcohajek** [planetteamspeak/ts3phpframework#30]
Hey guys,

I wanted to interact with ts3 viewer (example: click on client get a messagebox with options to kick/ban him, edit channels, etc) But i can't find a way how to do this.. can you give me a little input?

Currently im creating the teamspeak viewer like that:

```
$ts3->getViewer(new TeamSpeak3_Viewer_Html(URL::asset('assets/libs/TeamSpeak3/img/viewer/') .'/', URL::asset('assets/libs/TeamSpeak3/img/flags/') .'/', "data:image"));
```

I installed the framework to my project via composer if this makes any differences

**Comment by ronindesign** [comment]
It would probably be easiest to extend `TeamSpeak3_Viewer_Html` and override methods as needed:
```php
class TeamSpeak3_Viewer_Interactive extends TeamSpeak3_Viewer_Html
{
// ...
}
```

You could also write your own viewer:
```php
class TeamSpeak3_Viewer_Interactive implements TeamSpeak3_Viewer_Interface
{
// ...
}
```
[[ref](https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___viewer___html.html)]
