### ISSUE TITLE
New release with fixes 

### ISSUE THREAD

**Issue by ownede** [planetteamspeak/ts3phpframework#31]
Some issues, like #29 have been marked as "closed", but without any release.
We should avoid using `dev-master` composer version on production environments.

Is there any progress on new release with fixes?

**Comment by ronindesign** [comment]
Thank you for reporting this, we've pushed new release `1.1.25` and can be found on release page.

I don't believe we have auto-update / GitHub hook setup for Packagist yet. So release version update may take up to a week according to Packagist:
> **https://packagist.org/about - Update Schedule**
> Existing packages without auto-updating (GitHub/BitBucket hook) will be crawled once a week for updates.

Leaving open for now until Packagist version has updated to current release.

**Comment by ronindesign** [comment]
Packagist is now showing current release version as `1.1.25`:
> 1.1.25 ... 2017-05-08 19:47 UTC

https://packagist.org/packages/planetteamspeak/ts3-php-framework

Closing now that update has been confirmed. Please feel free to open if further assistance is needed!
