### ISSUE TITLE
Old framework version on packagist?

### ISSUE THREAD

**Issue by Wruczek** [planetteamspeak/ts3phpframework#35]
Hi!
I've noticed that version hosted on packagist does not contain important fixes like 4eceb5b381d638b12395ec45f68deb578ff27b8a, so I cant use it as Im also using PHP 7.1.

**Comment by Najsr** [comment]
Then use https://packagist.org/packages/fkubis/teamspeak-php-framework. I think it's better :)

**Comment by Wruczek** [comment]
Thanks for your reply, but this is not what Im looking for as it changes the code and added other things. I just want an up-to-date version of the official code ;)

**Comment by ronindesign** [comment]
Working on pushing to packagist, and system for releasing as mentioned here also #31

**Comment by ronindesign** [comment]
Quick up here, we've pushed version `1.1.25` as current release, and is available through GitHub.

We're waiting on Packagist crawl, as we are not yet using auto-update / GitHub hook on push, and this could take up to a week.

Leaving this open for now until we confirm new version on Packagist.

**Comment by ronindesign** [comment]
Packagist is now showing current release version as `1.1.25`:
> 1.1.25 ... 2017-05-08 19:47 UTC

https://packagist.org/packages/planetteamspeak/ts3-php-framework

Closing now that update has been confirmed. Please feel free to open if further assistance is needed!
