### ISSUE TITLE
PHP 7.1 -- unset($this)

### ISSUE THREAD

**Issue by Hisroyal** [planetteamspeak/ts3phpframework#37]
Hi,

"It's not allowed to re-assign $this, so why it should be allowed to unset() it. The following code worked in PHP 7, but will emit compilation error in PHP 7.1" from [wiki php](https://wiki.php.net/rfc/this_var)

unset($this); // Fatal error: Cannot unset $this

TeamSpeak3/Node/Server.php on line 2276
TeamSpeak3/Node/Servergroup.php on line 82

**Comment by ronindesign** [comment]
@Hisroyal I don't see the references you're citing.

On `Server.php:2276` I see:
```php
  /**
   * Starts the virtual server.
   *
   * @return void
   */
  public function start()
  {
```
Ref: https://github.com/planetteamspeak/ts3phpframework/blob/master/libraries/TeamSpeak3/Node/Server.php#L2276

And `Servergroup.php:82`:
```php
  /**
   * Creates a copy of the server group and returns the new groups ID.
   *
   * @param  string  $name
   * @param  integer $tsgid
   * @param  integer $type
   * @return integer
   */
  public function copy($name = null, $tsgid = 0, $type = TeamSpeak3::GROUP_DBTYPE_REGULAR)
  {
```
Ref: https://github.com/planetteamspeak/ts3phpframework/blob/master/libraries/TeamSpeak3/Node/Servergroup.php#L82

**Comment by Hisroyal** [comment]
i didn't see #21 sorry :)
