### ISSUE TITLE
Groups are sorted by internal id instead of sort id

### ISSUE THREAD

**Issue by Phoenix616** [planetteamspeak/ts3phpframework#41]
Groups that clients are in are currently sorted by their internal id instead of the value of the i_group_sort_id permission. This is extremely obvious with the icons when generating the viewer.

Teamspeak client:
![Clients in teamspeak client](https://i.imgur.com/uex7EFA.png)

Html viewer:
![Clients in html viewer](https://i.imgur.com/DKiJnIY.png)

**Comment by ronindesign** [comment]
I can reproduce this and confirm sorting does not depend on `i_group_sort_id`.
Thank you for the contribution in posting this, we appreciate it!

**Comment by ronindesign** [comment]
Hi @Phoenix616, I've created PR #43 to fix this issue.

In all the environments I used for testing and reproducing this bug, the updated logic appears to have fixed the lack of sorting on server group icons for clients in the viewer.

If you have a moment to download that version and test against your existing code / viewer, I would greatly appreciate it.

**Comment by Phoenix616** [comment]
Awesome! I will be testing it soon.

**Comment by ronindesign** [comment]
@Phoenix616 and update on if this is working for you?

I'll close for now, but we can absolutely reopen if you're still see issues.

**Comment by Phoenix616** [comment]
Ah, I forgot about this one. That fixes the icon sorting for me. Thanks!

**Comment by ronindesign** [comment]
Not a problem at all. Glad it working smoothly for you!
