### ISSUE TITLE
[Question] Version 2

### ISSUE THREAD

**Issue by thhan** [planetteamspeak/ts3phpframework#44]
I see this issue #20.

My question is, why do you not release your v2-alpha or v2-dev in this repository? I think it'll be greate, because we all can help you to release it faster and/or give feedback to some functions.

**Comment by ronindesign** [comment]
Glad you found the previous issue's discussion.

I completely agree with releasing an alpha of v2, however I'm not sure if there is even an alpha-stable version currently.

Last we heard it was in the works, but no confirmation on if it's reached a "complete enough" state to even work. My guess is there has not been much progress on this as other projects are getting priority possibly...

@svenpaulsen maybe you can update or comment on this?

**Comment by Sebi94nbg** [comment]
@svenpaulsen when do you expect to release the first version of v2?

**Comment by svenpaulsen** [comment]
I'll see what I can do around the holidays.

**Comment by thhan** [comment]
@svenpaulsen do will release version 2 soon or stopped you to developing version 2?

A short post will be nice, to get informed about the progress of this project.

Cheers,
Thomas

**Comment by thhan** [comment]
After one Year with out an answer from @svenpaulsen. I start to rewrite this project for psr-4.

Look at https://github.com/eSports-Alliance/teamspeak3-core

**Comment by ronindesign** [comment]
@thhan thanks for your contribution on this. We've needed PSR-4 for a while now, thanks for taking the step in rewriting. Once finished and testing is working again, I'd like to merge in your fork as V2!

**Comment by Sebi94nbg** [comment]
Please also add a guide "How to upgrade from v1 to v2", if necessary. :)

**Comment by ronindesign** [comment]
In the meantime, maybe we can also compile a list of any issues / comments about the upgrade process on a wiki page here.

**Comment by Sebi94nbg** [comment]
I've added a wiki page with some content and a basic structure: https://github.com/planetteamspeak/ts3phpframework/wiki/Upgrading-to-V2-from-V1 :)

Mhmm... I would not save comments or issues on a wiki page. I would use the issue system. It's better as you also can mark them as read and done (closed). ;)

**Comment by ronindesign** [comment]
Perfect, that's great, thanks for putting that together!

I was referring to an organized set of information for developers switching from v1 to v2 (e.g. "notes"). Basically what you've compiled already! :)
I would include considerations for updating composer configuration, testing (PHPUnit), code coverage, and especially things to watch out for when developers migrate their existing v1 code to v2.

**Comment by thhan** [comment]
I'll create a merge request as soon as i think it will be a greate version 2 ;)

**Comment by ronindesign** [comment]
I've got a dev branch ready for merge whenever PSR-4 is ready. We won't tag it v2 until it's ready! Thanks again!

**Comment by thhan** [comment]
I started to create a MockTCP and MockServerQuery class for unit test. I'm trying to emulate a TeamSpeak3-Server with this. 

Take a look at https://github.com/eSports-Alliance/teamspeak3-core/blob/master/src/Transport/MockTCP.php. 

I hope you can help me to complete the list of commands.

**Comment by ronindesign** [comment]
I worked on this a little myself for a few commands, but wasn't satisfied that it correctly mocked signal data as it comes from the real TS3 SA query server, especially in terms of transport / lower-level responses (encoding, line endings, timings, etc).

It should work well for higher-level, content tests, and something is definitely better than nothing; I'll see what I can contribute!

**Comment by thhan** [comment]
The idea behind the mock is, that we can testing nodes. It will be nice, when the mock can save states so you can change your nickname and the mock display your nickname in the client_list. But this is a feature for the future ;-)
