### ISSUE TITLE
TeamspeakAPI lost connection

### ISSUE THREAD

**Issue by thhan** [planetteamspeak/ts3phpframework#45]
`vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Transport/TCP.php:128 - connection to server '192.168.50.13:10011' lost`

I got after about 20 minutes this error-message. I don't know, why the script lost the connection. Can someone help me, please?

**Comment by ronindesign** [comment]
Please post a sample of your code where you're waiting logic is.

I believe there was a bug introduced with keepalive timeout, but it was patched.

Please make sure you're running most current version as well:
https://github.com/planetteamspeak/ts3phpframework/archive/master.zip

**Comment by thhan** [comment]
I used this framework in [Symfony-TeamSpeakBundle](https://github.com/eSports-Academy/ESATeamSpeakBundle/blob/master/Command/BotRunCommand.php). I can't explain me why the script lost the connection.

**Comment by ronindesign** [comment]
Thank you for the info, I'm looking into your code to see if I can find the reason.

I will update when I have more information.

**Comment by ronindesign** [comment]
I see in your `composer.json`:
```json
"require": {
    "php": ">=5.6",
    "symfony/symfony": ">=3.0.0",
    "planetteamspeak/ts3-php-framework": "^1.1"
  }
```

The current pre-release version for `ts3-php-framework` is `1.1.26` can you confirm this is the same version you have installed?

You probably need to move `ts3-php-framework` to your `required-dev` section:

```json
  "require": {
    "php": ">=5.6",
    "symfony/symfony": ">=3.0.0"
  },
  "require-dev": {
    "phpunit/phpunit": "3.7.*",
    "planetteamspeak/ts3-php-framework": "^1.1"
  }
```

The latest stable release is `1.1.24`, but the two pre-releases since then have a few bug fixes.

Please let us know if that works for you.

**Comment by thhan** [comment]
The version I used is `1.1.25` - I see in the commits, that only one bugfix for the html-viewer is updated. But this couldn't solved my problem.

**Comment by ronindesign** [comment]
Ok, I'm not sure why else you might be getting that timeout error.

The keepalive timeout limit for teamspeak is 10 minutes, so if there was no keepalive happening it should disconnect before your 20 minutes reported...

I'm unable to reproduce this on the framework alone using the basic examples.

Everything else in your code seems to be fine.

**Comment by ronindesign** [comment]
If you continue to have trouble with this, I might be able to download your code and try to troubleshoot myself...

I'm sorry I can't be more helpful at the moment!

**Comment by thhan** [comment]
Ah I have a idea. I forgot in the timeout function to update the client every 10 minutes before teamspeak will timeout the bot.

**Comment by ronindesign** [comment]
If your code is blocking and stopping the bot from running its keepalive, then that is a problem.

However, you shouldn't need any special code "update the client" every 10 minutes.
The keepalive logic is handled internally already.

Here is an example of a simple bot which includes the keepalive and does not timeout:
```php
// load framework files
require_once("libraries/TeamSpeak3/TeamSpeak3.php");
// connect to local server in non-blocking mode, authenticate and spawn an object for the virtual server on port 9987
$ts3_VirtualServer = TeamSpeak3::factory("serverquery://username:password@127.0.0.1:10011/?server_port=9987&blocking=0");
// get notified on incoming private messages
$ts3_VirtualServer->notifyRegister("textprivate");
// register a callback for notifyTextmessage events 
TeamSpeak3_Helper_Signal::getInstance()->subscribe("notifyTextmessage", "onTextmessage");
// wait for events
while(1) $ts3_VirtualServer->getAdapter()->wait();
// define a callback function
function onTextmessage(TeamSpeak3_Adapter_ServerQuery_Event $event, TeamSpeak3_Node_Host $host)
{
 echo "Client " . $event["invokername"] . " sent textmessage: " . $event["msg"];
}
```

**Comment by thhan** [comment]
``` php
$uri = sprintf("serverquery://%s:%s@%s:%s/?server_port=%s&timout=3&blocking=0%s&timeout=%s",
            $username,
            $password,
            $host,
            $query_port,
            $port,
            $nickname,
            $timeout);

        self::$teamSpeakInstance = \TeamSpeak3::factory($uri);
```
This is the factory. And I register a TimeOutEvent like this.

```php
public static function onTimeout($timeout, \TeamSpeak3_Adapter_ServerQuery $serverQuery)
    {

        if (false === file_exists(self::$pidFile)) {
            die();
        }

        if ($serverQuery->getQueryLastTimestamp() < time() - 290) {
            $serverQuery->request("clientupdate");
        }
    }
```
Is there any problems i couldn't see?

**Comment by ronindesign** [comment]
Your code should work, I see no problem.

**Comment by thhan** [comment]
I tested it now and it works :+1: thank you for you help

**Comment by ronindesign** [comment]
Glad it's working, please let us know if you run into any further trouble.
