### ISSUE TITLE
Which PHP versions are supported?

### ISSUE THREAD

**Issue by Sebi94nbg** [planetteamspeak/ts3phpframework#51]
> Fully object-oriented PHP 5 and E_STRICT compliant components

What about PHP 7.0 and 7.1? Are these versions also fully supported by the framework or not? Any known issues?

**Comment by thhan** [comment]
I usw 7.0 in my Projekt anderen it's Wirkung.

**Comment by thhan** [comment]
*I use 7.0 in my project and it's working.

**Comment by Sebi94nbg** [comment]
T9 is sometimes really funny. :D

Ok, thx for your feedback. When PHP 7.0 is working, 7.1 should work too. I'll test it soon and update the issue. :)

**Comment by ronindesign** [comment]
We try to support v7.0.x, and fix any bugs as a result, but we don't have much in the way of test coverage so we can't confirm for certain.

So far, not many issues are being reported, so we're hoping it's mostly stable.

In regards to v7.1, again we have not done much testing so can not say for certain.
If you find an issue, try searching the list of incompatibilities to check for possible cause:
http://php.net/manual/en/migration71.incompatible.php

I personally use v7.0 and v7.1, and haven't had any issues with my use cases.

Thanks for being willing to test and check.
If you're able to write up some unit tests, we can merge them in!
It would be a great help, regular testing would go along way with reducing risk of instability.

**Comment by jens1o** [comment]
What's up with PHP 7.2? It's coming out this month. :)

**Comment by ronindesign** [comment]
@jens1o true! We've not done any testing with 7.2 yet.

I will see if I can do some minimal tests this weekend and confirm v7.2 stability.

**Comment by Sebi94nbg** [comment]
Just tested a few things. PHP 7.1 is working so far. :)
