### ISSUE TITLE
Get latest server version string

### ISSUE THREAD

**Issue by Sebi94nbg** [planetteamspeak/ts3phpframework#53]
I want to get the latest published server version as string like `3.0.13.8`.

To archive this, I thought, this code is the correct one:

```
// load framework files
require_once("libraries/TeamSpeak3/TeamSpeak3.php");

// connect to default update server
$ts3_UpdateServer = TeamSpeak3::factory("update");

echo "Latest Version: " . $ts3_UpdateServer->getServerVersion();
```

But, it returns `3.0.10.1`. Which version is this? Why doesn't it return `3.0.13.8`?

**Comment by ronindesign** [comment]
Let me check on this and get back to you.

**Comment by svenpaulsen** [comment]
The TeamSpeak update server only returns the last server version with protocol compatibility. To query the latest versions use these URLs:

https://www.teamspeak.com/versions/client.json
https://www.teamspeak.com/versions/server.json

**Comment by Sebi94nbg** [comment]
@svenpaulsen can you maybe add a function to your framework to get the versions from these JSON files? This would be great.

**Comment by svenpaulsen** [comment]
I don't think there's a need to do that. Basically, it's as simple as this:

```php
$versions = json_decode(file_get_contents('https://www.teamspeak.com/versions/server.json'));

echo $versions->linux->x86_64->version;
```

**Comment by Sebi94nbg** [comment]
Mhmm, ok. Then I'll just use [json_decode()](http://php.net/manual/en/function.json-decode.php). Thx.
