### ISSUE TITLE
Offline virtual server: virtualserver_ip is empty, virtualserver_port not

### ISSUE THREAD

**Issue by Sebi94nbg** [planetteamspeak/ts3phpframework#56]
Hey, it's me - again. :D

I've just stopped one virtual server and tried to get some information using the URI option `use_offline_as_virtual`.

```
$TS3PHPFramework = new TeamSpeak3();

$uri = "serverquery://username:password@127.0.0.1:10011/?server_id=1337&blocking=0&use_offline_as_virtual";

$ts3_virtualserver = $TS3PHPFramework->factory("$uri");

var_dump($ts3_virtualserver->virtualserver_ip);
```
Unfortunately, the `virtualserver_ip` is just `null`. But the `virtualserver_port` is available and returns the correct port (eg. `9987`).

Is it technical just not possible to get the IP address too or is there something in the code of the framework or mine missing?

Btw: What exactly does this `blocking=0`? Does it tell the TeamSpeak instance, that the connection / user can't be banned due of possible flood attacks?

**Comment by thhan** [comment]
The `blocking` option is used to register callbacks by events. So your script can handle by example join_events or messages. Take a look to "[Create a Simple Bot waiting for Events](https://docs.planetteamspeak.com/ts3/php/framework/index.html#example14)"

**Comment by ronindesign** [comment]
@Sebi94nbg Sorry for delay in response, holidays around here!

I'm not 100% positive, but this looks like it is the intended effect.
It seems `virtualserver_ip` is not set when the server is not configured to bind to a specific IP (e.g. using config INI file).
Ref: http://forum.teamspeak.com/threads/60054-Problems-getting-the-current-Server-IP?p=266457#post266457

You could also try connecting directly to server query via telnet and get property via 'serverinfo` command:
```
TS3
Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.
use 1
error id=0 msg=ok
login serveradmin password
error id=0 msg=ok
serverinfo
...
 virtualserver_ip=999.999.999.999
...
error id=0 msg=ok
```
Again, this probably will be empty (as intended), but this will confirm it's not the framework.

Please follow-up if you have any other questions or would like more info on how `blocking` works.

**Comment by Sebi94nbg** [comment]
Thanks for your feedback. Ok, then I'll store the IP address in the database and fetch it from there, when TeamSpeak doesn't return it for offline servers.
