### ISSUE TITLE
Change shown possibility to connect as server query guest or as server query user in the Documentation

### ISSUE THREAD

**Issue by chaos234** [planetteamspeak/ts3phpframework#58]
I am not sure why this is hardcoded in this framework from what I have seen but it is not required to use every time the serveradmin login.

It is enough to have an valid Queryaccount which has only the req. rigths, not more and not less which means if you want to have a TS Viewer only then the TS3 Guestserver Query is still enough.

Horrible, that I must remove all this hardcoded stuff so please remove it and replace it with variables, thanks.

**Comment by ronindesign** [comment]
Please provide a reference to code or a snippet so we can review.

We'd love to clean it up so you don't have to!

**Comment by chaos234** [comment]
I have to correct me - sorry for that.

Referring to https://docs.planetteamspeak.com/ts3/php/framework/ you define a connection like:

`TeamSpeak3::factory("serverquery://username:password@127.0.0.1:10011/?server_port=9987");`

At this point I assumed to use the serveradmin data which isn't correct at all because you have allways the Guest Server Query so you should also add there the following line:

`TeamSpeak3::factory("serverquery://username:password@127.0.0.1:10011/?server_port=9987");`

It would also be fine to add it like this

`if(isset(username) && isset(password)) {
TeamSpeak3::factory("serverquery://username:password@127.0.0.1:10011/?server_port=9987");
} else {
TeamSpeak3::factory("serverquery://127.0.0.1:10011/?server_port=9987");}`

Or in shorter terms:

`((isset(username) && isset(password)) ? TeamSpeak3::factory("serverquery://username:password@127.0.0.1:10011/?server_port=9987"): TeamSpeak3::factory("serverquery://127.0.0.1:10011/?server_port=9987"));`

This is what I figured out on my own.

**Comment by ronindesign** [comment]
Thanks for adding more information, I appreciate it. Reviewing this now.

**Comment by ronindesign** [comment]
Oh, so you were able to find a solution that met your need?

Would you recommend adding these examples to the documentation?
Maybe that would help future users from having similar trouble.

**Comment by chaos234** [comment]
Indeed I would recommend this.

In addition you should also make a notice to tell users that they should never directly replace "username:password", they should replace it like this:

`TeamSpeak3::factory("serverquery://" . $queryUser . ":" . $queryUserPassword . "@" . $serverAddress . ":" . $serverQueryPort . "/?server_port=" . $serverPort)`

It is much more safer because if someone is hacking into your system and find the fle containing such a line hardcoded you'll get into trouble if you have past your serveradmin values there.

I safed the data over a mysql/mariaDB table and hashed the password incl. a salt value to make it more safe if the DB get's hacked to.

A config file instead of a DB would also work but how would you then protect the credentials if your FTP gets hacked? But this is onyl a sidenote at this point. ;)
