### ISSUE TITLE
i_icon_id

### ISSUE THREAD

**Issue by qeekus** [planetteamspeak/ts3phpframework#65]
its work
$icon = '1697275748';
 $ts3_VirtualServer->channelGetById(cid)->permAssign("i_icon_id", "$icon");
if
$icon = '4262397297';
not work (error: convert error)

**Comment by ronindesign** [comment]
It would help if you provided more information:
- PHP version
- Full copy of error message (and exception trace, if any)

The only other thing I can think is that for `$icon = '4262397297';`.
We have `4262397297` being larger than the maximum positive value for a (signed) 32-bit integer.

I noticed some entries in the changelog around convert errors resulting from integer size / limits.
It's possible this could be a similar problem, but will need more info before I can test further.

**Comment by ronindesign** [comment]
Also, @qeekus please see:
https://forum.teamspeak.com/threads/54132-API-TS3-PHP-Framework?p=415394#post415394

Looks like the same issue, again the int there is over max signed Int32, but issue might be related to wrong ID after upload or some such.

**Comment by qeekus** [comment]
I solved too in php file /Node/Server.php.
  public function iconUpload($data)
  {
    $crc = crc32(substr($data, 1, 2));  
    //$crc   = crc32($data);
    $size = strlen($data);

    $upload   = $this->transferInitUpload(rand(0x0000, 0xFFFF), 0, "/icon_" . $crc, $size);
    $transfer = TeamSpeak3::factory("filetransfer://" . (strstr($upload["host"], ":") !== FALSE ? "[" . $upload["host"] . "]" : $upload["host"]) . ":" . $upload["port"]);

    $transfer->upload($upload["ftkey"], $upload["seekpos"], $data);

    return $crc;
  }

**Comment by ronindesign** [comment]
@qeekus you probably got luck when you tested your fix...

This will still return integers greater than Int32 (signed) max size.
`$crc = crc32(substr($data, 1, 2));`

`crc32` is just a hashing function of whatever you pass in, so the resulting hash can be variable in size (even when passing in string of length 2).
http://us2.php.net/manual/en/function.crc32.php

> For a more portable solution you may also consider the generic hash(). hash("crc32b", $str) will return the same string as str_pad(dechex(crc32($str)), 8, '0', STR_PAD_LEFT).

We'll work on getting this patched and tested, sorry about the inconvenience!

**Comment by qeekus** [comment]
yep,
`$crc = substr(crc32($data), 1, 2);`

**Comment by ronindesign** [comment]
To decrease the chance of collision, you may want to increase the substring size.
A length of 9 would always result in value safely less than max Int32:
`$crc = substr(crc32($data), 0, 9);`

This way will be less likely to save over existing icon with same name when.
A substring of 2 digits means only 10*10 = 100 possible icon names, not very many...

**Comment by svenpaulsen** [comment]
Sorry, but this is working as expected... An icon ID is basically the crc32 polynomial of the icon file. The server stores it as an unsigned integer equal to the icon ID that is used as a value for the i_icon_id permission.

If you're setting the i_icon_id permission directly, you'll need to calculate the correct value. However... if you update the icon ID using the `channeledit` command, the TeamSpeak Server will to the job for you. So this should be working:

```php
$channel->channel_icon_id = 4262397297;
```

**Comment by svenpaulsen** [comment]
Please re-test with the latest master. I've added a helper function to convert unsigned icon IDs to their signed version:

```php
// should print -32569999
echo TeamSpeak3_Helper_Convert::iconId(4262397297);
```

**Comment by qeekus** [comment]
$ts3_VirtualServer->execute("channeledit cid=" . $current_cid . " channel_icon_id=" . $icon);  ?
all right?

**Comment by qeekus** [comment]
probably worked. I tested, there are no errors. thx
