### ISSUE TITLE
Permanent server passwords

### ISSUE THREAD

**Issue by MegaITA** [planetteamspeak/ts3phpframework#72]
Is there a way to put a permanent server password? I've seen that in the docs you can create a temporary server password, but i need to put a permanent server password option

**Comment by ronindesign** [comment]
Not sure what you're referring to? Could you give an example of how you would do the _temporary password_ or link to the relevant docs for reference?

If you you just mean a server password for new users when they connect, this should be permanent as is done here directly via the server query:
`serveredit virtualserver_modify_password=mypassword`

Ref:
`b_virtualserver_modify_password`
`VIRTUALSERVER_PASSWORD` (virtual server property)

Maybe describe what or how the password is failing to remain / stay permanent?

**Comment by MegaITA** [comment]
I'd like to use tempPasswordCreate() but permanently so if anyone wants to join has to put the password.

**Comment by ronindesign** [comment]
So if you want to set the virtual server password, one way is by simply modifying the server:
```php
$ts3server = TeamSpeak3::factory(...);
$ts3server->modify(['virtualserver_modify_password' => 'mypassword']);
```
Ref: https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___server.html#a26187c386dd2da50aa5e08d7c7fb9c83

**Comment by MegaITA** [comment]
Thank you, where do I get all the properties I can set?

**Comment by ronindesign** [comment]
@MegaITA I usually reference the [TS3 Server Query Manual](http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf#page=40)
