### ISSUE TITLE
Encrypted ServerQuery connection with v1.1.32 and newer

### ISSUE THREAD

**Issue by Sebi94nbg** [planetteamspeak/ts3phpframework#78]
Hey,
I've just updated my ts3-php-framework from 1.1.28 to 1.1.32 (current latest) and now, I'm always getting this error message using URI option `tls=1`:

> stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

I've seen this change in the release notes:

>  ! TeamSpeak3::factory() uri now features an optional parameter to enable the
>    encrypted ServerQuery connections via SSL/TLS

But I couldn't figure out, how I can use encrypted / SSL/TLS secured ServerQuery connections now.

To what do I need to change my URI?

`serverquery://serveradmin:secretPassword@127.0.0.1:10011/?tls=1`

**Comment by ronindesign** [comment]
Yep, I had this same problem / error when I tried to write tests for TLS.

I think mine said something about failing TLS / SSL handshake.

I have not had time to figure it out / troubleshoot it.

Some initial thoughts I had:
- Check OpenSSL version installed (especially for your distro) and what it's default TLS setting is.
OpenSSL wiki even has a section [Version Tricks](https://wiki.openssl.org/index.php/SSL_and_TLS_Protocols#versions_tricks)
- Might need to check SSL / Certificate config. It should just work, but.... :/

**Comment by Sebi94nbg** [comment]
Mhmm, OpenSSL is installed and enabled (`phpinfo()` confirms this), but it keeps returning this message:
```
$ openssl s_client -connect <server_ip>:10011 -tls1_2
CONNECTED(00000003)
140412319991552:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:252:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 102 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1525182636
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```
Do I may need to configure / enable TLS support on the TeamSpeak server side? Because a port/ssl cipher scan returns nothing:
```
$ nmap --script ssl-enum-ciphers -p 10011 <server_ip>

Starting Nmap 7.01 ( https://nmap.org ) at 2018-05-01 14:10 UTC
Nmap scan report for ipdc-vs00019.4g-server.eu (185.242.113.114)
Host is up (0.11s latency).
PORT      STATE SERVICE
10011/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.76 seconds
$ nmap --script ssl-enum-ciphers -p 10011 185.242.113.114

Starting Nmap 7.01 ( https://nmap.org ) at 2018-05-01 14:10 UTC
Nmap scan report for ipdc-vs00019.4g-server.eu (185.242.113.114)
Host is up (0.11s latency).
PORT      STATE SERVICE
10011/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.76 seconds
```

**Comment by Sebi94nbg** [comment]
Where does the library get this config value from?
https://github.com/planetteamspeak/ts3phpframework/blob/167fa69e7b48b17fe8783597a9e6c1be5402ff09/libraries/TeamSpeak3/Transport/TCP.php#L55

Even when I change my URI from `tls=1` to `tls=0`, it says, that this option has the value `1`. So I'm wondering, where it gets it from.

@svenpaulsen can you may help us here?

**Comment by ronindesign** [comment]
Re: tls config line - that's set in TeamSpeak3::factory when it decomposes
URI. When it returns the node, the object has `$node->config` set with
element.

**Comment by ronindesign** [comment]
Also, note that: 
`!empty($this->config["tls"]) == true` when `tls=1` AND when `tls=0`, it's a `!empty()` check.
So to test you'll need to remove the query parameter entirely.

**Comment by Sebi94nbg** [comment]
Yeah, I saw, that it's not checking the value.

I did just `var_dump($this->config["tls"])` before this `if()` line and it always returned `1`, even when I used `tls=0`.

**Comment by ronindesign** [comment]
https://github.com/planetteamspeak/ts3phpframework/blob/master/libraries/TeamSpeak3/TeamSpeak3.php#L323

`"tls" => (int) $uri->getQueryVar("tls", 0)`
Maybe `$uri->getQueryVar("tls", 0)` returns string instead of int? For which `(int) $uri->getQueryVar("tls", 0) == (int) "1" == (int) "0"`?

**Comment by Sebi94nbg** [comment]
Yeah, that‘s what I thougt. So this option is only for TeaSpeak, right?

Sent from my smartphone

**Comment by svenpaulsen** [comment]
Correct.
