### ISSUE TITLE
invalid clientID when client is offline

### ISSUE THREAD

**Issue by MasterPuffin** [planetteamspeak/ts3phpframework#82]
I use the following code to delete all server groups of a client
```
$oldTSUID = "TS USER ID HERE=";
try{
  require_once '../config/teamspeak.php';
  $clientdbid = $ts3->clientFindDb($oldTSUID, TRUE);
  $client = $ts3->clientGetByDbid($clientdbid[0]);
  $groupsArr = explode(',', $client['client_servergroups']);
  print_r($groupsArr);
  foreach($groupsArr as $group){
    $ts3->serverGroupClientDel($group, $clientdbid);
  }
} catch(Exception $e) {
  echo "TS Fehler!<br/>ErrorID: <b>". $e->getCode() ."</b>; Error Message: <b>". $e->getMessage() ."</b>;";
}
```
This works fine when the user is connected to the TS Server but when he is offline the function
`$client = $ts3->clientGetByDbid($clientdbid[0]);` returns an emtpy $client variable and I get the error `ErrorID: 512; Error Message: invalid clientID;`

Edit: This also happens, when using the `clientGetByUid()` function

**Comment by svenpaulsen** [comment]
This is working as intended. All `clientGetBy****()` methods will return a `TeamSpeak3_Node_Client` object which requires the client to be online. To remove a client from all groups, do something like this:

```php
$cldbids = $ts3->clientFindDb($cluid, TRUE);

foreach($ts3->clientGetServerGroupsByDbid($cldbids[0]) as $sgid => $group)
{
  $ts3->serverGroupClientDel($sgid, $cldbids[0]);
}
```
