### ISSUE TITLE
Object of class TeamSpeak3_Helper_String could not be converted to int

### ISSUE THREAD

**Issue by Zerefdev** [planetteamspeak/ts3phpframework#83]
Hello, 
I was testing the tsviewer example provided with the framework files..
It works but it also shows those notices:
`Notice: Object of class TeamSpeak3_Helper_String could not be converted to int in /public_html/ts3/lib/Node/Channel.php on line 549`

`Notice: Object of class TeamSpeak3_Helper_String could not be converted to int in /public_html/ts3/lib/Viewer/Html.php on line 507`

`Notice: Object of class TeamSpeak3_Helper_String could not be converted to int in /public_html/ts3/lib/Node/Abstract.php on line 126`

How can I fix it?
Regards

**Comment by ronindesign** [comment]
You can use php INI options to disable displaying warnings, notices, errors, etc.
(In the future, providing your PHP version can help us help you better.)
Example:
```php
<?php

// Turn off all error reporting
error_reporting(0);

// Report simple running errors
error_reporting(E_ERROR | E_WARNING | E_PARSE);

// Reporting E_NOTICE can be good too (to report uninitialized
// variables or catch variable name misspellings ...)
error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE);

// Report all errors except E_NOTICE
error_reporting(E_ALL & ~E_NOTICE);

// Report all PHP errors (see changelog)
error_reporting(E_ALL);

// Report all PHP errors
error_reporting(-1);

// Same as error_reporting(E_ALL);
ini_set('error_reporting', E_ALL);

// ... your tsviewer code
```
Reference:
http://php.net/manual/en/function.error-reporting.php

**Comment by Zerefdev** [comment]
@ronindesign 
Thank you for your answer,
I am using php 7.2 on debian 9
Is that means these notices are not harmful? I've never seen them
Regards

**Comment by ronindesign** [comment]
Correct, not harmful.
This notice is expected since we're using numerical operators on the helper string object.
For example:
```
if($this["channel_maxclients"] != -1 && $this["channel_maxclients"] <= $this["total_clients"])
{
...
}
```
This in turn, is happening because we're storing responses from server query as strings, i.e. `(str) "0"` instead of just `(int) 0`.
So we get a notice about the implicit type coercion, but it should be working correctly!

We'll make a note to add a test for this. Thanks for reporting it!

**Comment by Zerefdev** [comment]
Thanks for the explanation
