### ISSUE TITLE
Get an online client session time

### ISSUE THREAD

**Issue by realKitsune** [planetteamspeak/ts3phpframework#84]
Hello,

I've been doing a web console for my teamspeak, and I'd like to show how much time an user is connected.
I'm not talking about total connection time since Teamspeak I know doesn't store it, but I want the current session time (the one that you can get on client informations when right clicking a user).

I tried things like $ts3_Client['client_connection_time'] , $ts3_Client['client_session_time'], etc.... 
I know you can get client_idle_time, but I don't know for session_time

I hope this is possible

**Comment by ronindesign** [comment]
I haven't tested recently, but you might be able to calculate delta from:
`CLIENT_LASTCONNECTED`.
_Creation date and time of the client's last connection to the server as UTC timestamp_
Ref: [Server Query Manual - Client Properties](http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf#page=45)

For example:
```php
$online_time = time() - $ts3_Client['client_lastconnected'];
echo "Client online for " . $online_time . " seconds";
```
(Of course, you can also feed the time delta into `date()` for a more human format)

**Comment by realKitsune** [comment]
Hey,
Thanks it's working  !

Any idea why for example, when I'm connected since one hour, it says one day and 2 hours ?
I had to do this to counter the problem:

`            $info_SessionTime = time() - $ts3_Client['client_lastconnected'];
            if($info_SessionTime > 172800){
            	$info_connectedTime = date("j \j\o\u\\r\s H:i:s", $info_SessionTime - 3600 - 86400);
            }elseif($info_SessionTime > 86400){
            	$info_connectedTime = date("j \j\o\u\\r H:i:s", $info_SessionTime - 3600 - 86400);
            }else{
            	$info_connectedTime = date("H:i:s", $info_SessionTime - 3600);
            }
`

**Comment by 0stone0** [comment]
Hi,

Are the value's as expected? I'm getting some random value's. Pretty sure the code is fine.

Does anybody knows why the [B]client_lastconnected[/B] doesn't reset? 
Found some results on google and this forum but no solid solution. 

Code:
```
// Get clients
$clients = $ts3_VirtualServer->clientList();
foreach ($clients as $client) 
    $db_id = $client['client_database_id'];
    $extraInfo = $client->clientInfoDb($db_id);

    $onlineFor = time() - $extraInfo['client_lastconnected'];
    $time = sprintf('%02d:%02d:%02d', ($onlineFor/3600),($onlineFor/60%60), $onlineFor%60);

    echo 'Seconds:      ' . $onlineFor . PHP_EOL . 'HH:MM:SS:     ' . $time . PHP_EOL .'___________________________' . PHP_EOL;
}
```


Result:

```
Client Count..........5

Seconds:      5930
HH:MM:SS:     01:38:50
___________________________
Seconds:      14255
HH:MM:SS:     03:57:35
___________________________
Seconds:      2024587
HH:MM:SS:     562:23:07
___________________________
Seconds:      1758203
HH:MM:SS:     488:23:23
___________________________
Seconds:      5447
HH:MM:SS:     01:30:47
___________________________
Seconds:      1743250
HH:MM:SS:     484:14:10
___________________________

```

Some are obvious wrong. Have tried a lot without success

**Comment by realKitsune** [comment]
Since you are showing online clients you can simply use $client['client_lastconnected] instead of $client->clientInfoDb($db_id);

It worked for me,I had almost the accurate values except that I had to substract one hour, or one day one hour if client is online for 1day+

Some of results for me:

Temps de connexion 5 jours 13:17:27
Temps de connexion 12:29:37
Temps de connexion 07:10:51

**Comment by 0stone0** [comment]
Ah great. I thought that info was only available trough infoDb. Found it on the teamspeak forum. That was the mistake:

```
// Get clients
$clients = $ts3_VirtualServer->clientList();
foreach ($clients as $client) {

   $db_id = $client['client_database_id'];
   $extraInfo = $client->clientInfoDb($db_id);

    $t = time();
    $onlineFor0 = $t - $client['client_lastconnected'];
    $onlineFor1 = $t - $extraInfo['client_lastconnected'];

   echo "1: ${onlineFor0}\n2: ${onlineFor1}";
}
```

output:
```
1: 4
2: 1769917
```

Thx for the fast reply!
