### ISSUE TITLE
How to get NodeInfo for server virtual?

### ISSUE THREAD

**Issue by ph1823** [planetteamspeak/ts3phpframework#88]
Hello, current I am looking for retrieve information virtualservers maxclients I found for the number of client but not for this one, I saw that in the node info there was except that I do not know how to recover it. Can you help me please ?

Thank for your reply and your help!

**Comment by ronindesign** [comment]
All node objects have (array) `nodeInfo` property which can be accessed a number of ways:
- Explicitly by getter [TeamSpeak3_Node_Abstract::getProperty()](https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___abstract.html#ad02d1c1c924c342b644e28e923edac19).
E.g. `$server->getProperty('virtualserver_maxclients')`
- Implicitly by magic `__get` method.
E.g. `$server['virtualserver_maxclients']`
- Implicitly through [TeamSpeak3_Node_Abstract::getInfo()](https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___abstract.html#ac60d6af1acba9d78d719d4b86e987c07).
E.g. `$server->getInfo()['virtualserver_maxclients']`

To see what properties are available, you might try `print_r` or `var_dump` on `nodeInfo()`:
```php
print_r($server->nodeInfo());
```

**Comment by ph1823** [comment]
I had already tested the $ server ['virtualserver_maxclients'] and it returned me an empty element. Just like the $ server-> getProperty ('virtualserver_maxclients'), I do not understand why it returns empty. Yet when I do a var_dump ($ server) I have an array with a nodeInfo array that contains virtualserver_maxclients. And when I print_r ($ server-> getServer () -> getProperty ('nodeInfo')); it returns nil too, I have no error except for the getProperty I ca: node 'TeamSpeak3_Node_Channel' has no property named nodeInfo (or virtualserver_maxclients) how to solve this problem? Thank you for your reply!

**Comment by ronindesign** [comment]
Are you making sure to select a virtual server, by specifying port / id in
the TeamSpeak3 factory?

**Comment by ronindesign** [comment]
Glad it's working for you.

Closing this for now, please comment again if you need further assistance.
