### ISSUE TITLE
PHP <5.5 compatibility

### ISSUE THREAD

**Issue by yonilerner** [planetteamspeak/ts3phpframework#93]
I know the recommended PHP version is 7+, but we are stuck on PHP 5.3 and trying to run newer versions of this library. The [site](https://docs.planetteamspeak.com/ts3/php/framework/index.html) claims that it works with PHP 5.2, but the code seems to be using [boolval](http://php.net/manual/en/function.boolval.php). So far we've managed to get it working by just filling in that method before calling any code here, but I figured I would point this out, in case you either want to remove use of boolval, change the site, or something else.

Thanks

**Comment by ronindesign** [comment]
Yes, the site documentation is old. We tried for a very long time to maintain backwards comparability, almost as a feature.

Yet, this becomes increasingly harder with the advent of testing, performance enhancement and especially language breaking features (from one major version to the next).

It is unfortunate, as I realize there still exists older environments using old versions of PHP.
If there is enough interest in this, we may think about a backward compatible, feature-basic branch.

That being said, we've definitely tried to minimize the "refactoring" for new PHP7+ features.
So, it might be a very realistic option to fork or branch master and tweak the non-compatible parts for their PHP5 equivalents...

**Comment by yonilerner** [comment]
Understood. Im not sure I have the ability to maintain a fork right now, but hypothetically, if I did, what would be the process for doing so in terms of attempting to maintain at least feature/API parity, if not strict compatibility at the lowest level?

Thanks for everything, this tool is absolutely fantastic

**Comment by ronindesign** [comment]
Well, I mean if you want to do the initial work on a feature branch, we can help maintain it if you're up for doing the work of reverting the non-PHP5 code back to PHP5 variants.

Again, we try really hard not to go crazy with using non-backward compatible features of PHP7.
New features are typically implemented in compatible manner.
When there is something non-compatible, it should only be minor difference and easily tweaked to be compatible for PHP5.
Thus, ideally we should just be able to directly merge new features down stream in to a "compatibility release".

Maintenance-wise, it should not be too much work to maintain something compatible with PHP5, this isn't rocket science and we're not using any cutting-edge features demanding PHP7.

**Comment by yonilerner** [comment]
Sounds good. The features we mostly use are the viewer, token generation, and group management, so we probably wont run into every potential failure, but Ill start a PR to fix the one issue (boolval) that we have had so far.

Thanks!

**Comment by ronindesign** [comment]
Fantastic, that would be awesome!

If you run into any obstacles or any issues with time constraints, don't hesitate to send out a flare!
Given that this will be useful to people, we definitely want to support and help in facilitating this.

Thanks again for posting the issue and follow-up.

**Comment by yonilerner** [comment]
I made the above PR, but Im having difficulty running the tests. I've never used phpunit before and I have very limited exposure to composer; after installing the packages (`composer install` and `composer require --dev` for the packages I added), running `phpunit --no-coverage` is reporting a ton of errors indicating that it cant find classes:
```
17) Tests\Unit\Transport\UDPTest::testDisconnect
Error: Class 'PHPUnit\Framework\Constraint\IsType' not found

/home/yonil/code/ts3phpframework/tests/Unit/Transport/UDPTest.php:111
```
Am I making an obvious mistake here? Thanks

**Comment by yonilerner** [comment]
Also, the only non-error failure Im getting is:
```
There was 1 failure:

1) StringTest::testIsInt
Failed asserting that false matches expected true.

/home/yonil/code/ts3phpframework/tests/Unit/Helper/StringTest.php:104
```
That test doesnt seem to rely on any code that I touched, so Im not sure why it would be failing.

**Comment by ronindesign** [comment]
Re: testing / PHPUnit - that error is a direct result of using older than PHP7.
PHPUnit in the new version uses namespace path for `IsType`, I thought we implemented backward compatible fix for this, but maybe it's still on the testing branch :(
(Ah here it is see below)

That single test is an expected failure, it is the only expected one.
It's a result of previous discussion (there's a closed issue regarding it), but basically it's intended that it fails until we can implement and confirm a fix for it.
All this to say, that it can be safely ignored and you will see it fail each time, as expected.

So we add alias for backwards compatible PHPUnit.
This is my testing bootstrap located at `tests/bootstrap.php`:
```php
➜  ts3phpframework git:(testing) ✗ cat tests/bootstrap.php 
<?php

$file = __DIR__ . '/../vendor/autoload.php';
if (!file_exists($file)) {
    $file = __DIR__ . '/../../../vendor/autoload.php';
    if (!file_exists($file)) {
        throw new RuntimeException('Install dependencies to run test suite.');
    }
}

$autoload = require_once $file;

// Make PHPUnit 6 tests backward compatible for PHPUnit 5 code base
if (PHP_VERSION_ID < 70000) {
  class_alias('PHPUnit_Framework_Constraint_IsType', 'PHPUnit\Framework\Constraint\IsType');
}%
```

Please also note, you may find more up-to-date tests on my downstream testing branch, I'm a bit ahead in terms of testing (as it's not quite stable enough to merge back up to master repo and I don't want to confuse / hinder new users):
https://github.com/ronindesign/ts3phpframework/tree/testing

Also, the wiki on my downstream repo has a lot more information, including a page on testing:
https://github.com/ronindesign/ts3phpframework/wiki/Testing
(again, only downstream as we're not sure what will make the final cut and go back up into master repo)

Keep the questions coming if you run into any further trouble or have additional questions!

**Comment by yonilerner** [comment]
Hm thats strange. The system Im targeting is PHP 5.3, but my computer is on PHP 7.2.7, so I wouldnt expect this:
```
2018-08-14 6:02PM  ✘ ⮀  ~CODE/ts3phpframework ⮀  ⭠ setup-compatibility-checking ⮀  php -v
PHP 7.2.7-0ubuntu0.18.04.2 (cli) (built: Jul  4 2018 16:55:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.7-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies
2018-08-14 6:02PM ⮀  ~CODE/ts3phpframework ⮀  ⭠ setup-compatibility-checking ⮀  phpunit
PHPUnit 5.5.4 by Sebastian Bergmann and contributors.
```

I think for now I'll stick to `master`. The CI system reported a failure for that one test, but I dont think there were any others, so that probably means I didnt break anything.

**Comment by yonilerner** [comment]
Ok so this is kinda strange. Im using PHP 7, but since Im on PHP Unit 5, Im having the compatibility issue. I cant seem to install PHP Unit 6:
```
2018-08-14 6:17PM  ✘ ⮀  ~CODE/ts3phpframework ⮀  ⭠ setup-compatibility-checking ±⮀  composer require 'phpunit/phpunit=6'
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: sebastian/exporter[2.0.0, 1.2.2].
    - Can only install one of: sebastian/exporter[2.0.0, 1.2.2].
    - Can only install one of: sebastian/exporter[2.0.0, 1.2.2].
    - phpunit/phpunit 6.0.0 requires sebastian/exporter ^2.0 -> satisfiable by sebastian/exporter[2.0.0].
    - Installation request for phpunit/phpunit 6 -> satisfiable by phpunit/phpunit[6.0.0].
    - Installation request for sebastian/exporter (locked at 1.2.2) -> satisfiable by sebastian/exporter[1.2.2].


Installation failed, reverting ./composer.json to its original content.
```
So for now Im stuck on PHP Unit 5. However, changing your Boostrap to use `PHP_VERSION_ID < 80000` (which would eval to true for me on PHP 7) allowed the tests to all pass (except for `testIsInt`). So I ended up adding this:
```php
$parsed_phpunit_version = `./vendor/bin/phpunit --version | head -n 1 | tr ' ' '\n' | head -n 2 | tail -n 1 | head -c 1`;
if (!is_null($parsed_phpunit_version) && $parsed_phpunit_version < 6) {
    class_alias('PHPUnit_Framework_Constraint_IsType', 'PHPUnit\Framework\Constraint\IsType');
}
```
And now running `phpunit --no-coverage` works as expected.

**Comment by yonilerner** [comment]
To clarify: I didnt touch the PHP_VERSION_ID check, I added this additional check for the PHPUnit version using shell trickery (could have been nicer if I used awk or sed, but I wanted it to be as cross-platform as possible). Its in the PR

**Comment by ronindesign** [comment]
Yeah, the issue initially is result of PHPUnit installed, but which one gets installed is dependent on a few things with composer, so I ran into the same issue as you.

You're absolutely right, my check was one way, so I appreciate you adding the PHPUnit check.
Sorry you ran into this, the testing branch / environment is still pretty fresh, so we haven't ironed out all the usability issues yet.

Ultimately, I feel like we've got CI setup to mirror most of our targeted environments, so as long as it passes there (ant it matches your target env as well), then it should cover all bases and be good to go.

**Comment by ronindesign** [comment]
Appreciate your understanding on this!

Yeah, I'm glad there was only that one issue. I agree regarding minimality, and like I've said, we've tried pretty hard to not go feature-crazy with PHP7, as we understand some environments are still tied to PHP5, so that's great.

However, regarding fork vs branching, and as you said, I think the most sane or ideal thing would be to just keep things merged into master and (hopefully) maintain PHP5 compatibility.

At some point soon though, we're going to have to make the split.
Whether that's by bumping major version to v2.X for PHP7 and only back-porting bug fixes to v1.X for PHP5 or having a standalone PHP5 compatible fork, is more of an organizational concern and less of a technical one, at least how it seems to me.
In either case we can still merge across forks / branches, and will still have the same overhead in refactoring for PHP5 when new code is added to master that uses PHP7 features.

Agree, I think we're on the same page here, so I'll close this issue for now and we'll continue on with PR.
